//*
// # Chain of Trust Proof
// Proof that some data belongs to the network's chain of trust, starting from
// the genesis network whose address book hash formed the ledger id. (In the
// current system, this data is always a hinTS verification key.)
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: chain_of_trust_proof.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainOfTrustProof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Proof:
	//
	//	*ChainOfTrustProof_NodeSignatures
	//	*ChainOfTrustProof_WrapsProof
	Proof         isChainOfTrustProof_Proof `protobuf_oneof:"proof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainOfTrustProof) Reset() {
	*x = ChainOfTrustProof{}
	mi := &file_chain_of_trust_proof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainOfTrustProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainOfTrustProof) ProtoMessage() {}

func (x *ChainOfTrustProof) ProtoReflect() protoreflect.Message {
	mi := &file_chain_of_trust_proof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainOfTrustProof.ProtoReflect.Descriptor instead.
func (*ChainOfTrustProof) Descriptor() ([]byte, []int) {
	return file_chain_of_trust_proof_proto_rawDescGZIP(), []int{0}
}

func (x *ChainOfTrustProof) GetProof() isChainOfTrustProof_Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ChainOfTrustProof) GetNodeSignatures() *NodeSignatures {
	if x != nil {
		if x, ok := x.Proof.(*ChainOfTrustProof_NodeSignatures); ok {
			return x.NodeSignatures
		}
	}
	return nil
}

func (x *ChainOfTrustProof) GetWrapsProof() []byte {
	if x != nil {
		if x, ok := x.Proof.(*ChainOfTrustProof_WrapsProof); ok {
			return x.WrapsProof
		}
	}
	return nil
}

type isChainOfTrustProof_Proof interface {
	isChainOfTrustProof_Proof()
}

type ChainOfTrustProof_NodeSignatures struct {
	// *
	// If there is not yet a SNARK proving the chain of trust from ledger id to
	// the hinTS verification key, the explicit list of Schnorr signatures on
	// the concatenation of the ledger id and genesis hinTS verification key
	// that serve as witnesses for the SNARK prover algorithm.
	NodeSignatures *NodeSignatures `protobuf:"bytes,1,opt,name=node_signatures,json=nodeSignatures,proto3,oneof"`
}

type ChainOfTrustProof_WrapsProof struct {
	// *
	// If known, a ZK-compressed SNARK proof proving the chain of trust from
	// the ledger id to this hinTS verification key.
	WrapsProof []byte `protobuf:"bytes,2,opt,name=wraps_proof,json=wrapsProof,proto3,oneof"`
}

func (*ChainOfTrustProof_NodeSignatures) isChainOfTrustProof_Proof() {}

func (*ChainOfTrustProof_WrapsProof) isChainOfTrustProof_Proof() {}

// *
// A list of valid node signatures on some data assumed known from the context
// of the message, ordered by node id.
// <p>
// Can be used to prove the genesis hinTS verification key in a block proof; but
// not succinct and not recursive; hence in normal operations with TSS, used only
// until the first recursive proof is available.
type NodeSignatures struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeSignatures []*NodeSignature       `protobuf:"bytes,1,rep,name=node_signatures,json=nodeSignatures,proto3" json:"node_signatures,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeSignatures) Reset() {
	*x = NodeSignatures{}
	mi := &file_chain_of_trust_proof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSignatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSignatures) ProtoMessage() {}

func (x *NodeSignatures) ProtoReflect() protoreflect.Message {
	mi := &file_chain_of_trust_proof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSignatures.ProtoReflect.Descriptor instead.
func (*NodeSignatures) Descriptor() ([]byte, []int) {
	return file_chain_of_trust_proof_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSignatures) GetNodeSignatures() []*NodeSignature {
	if x != nil {
		return x.NodeSignatures
	}
	return nil
}

// *
// A signature from a node on some data assumed known from the context of the
// message.
type NodeSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The node id of the signer.
	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// *
	// The signature.
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSignature) Reset() {
	*x = NodeSignature{}
	mi := &file_chain_of_trust_proof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSignature) ProtoMessage() {}

func (x *NodeSignature) ProtoReflect() protoreflect.Message {
	mi := &file_chain_of_trust_proof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSignature.ProtoReflect.Descriptor instead.
func (*NodeSignature) Descriptor() ([]byte, []int) {
	return file_chain_of_trust_proof_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSignature) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_chain_of_trust_proof_proto protoreflect.FileDescriptor

const file_chain_of_trust_proof_proto_rawDesc = "" +
	"\n" +
	"\x1achain_of_trust_proof.proto\x12\x1ccom.hedera.hapi.block.stream\"\x98\x01\n" +
	"\x11ChainOfTrustProof\x12W\n" +
	"\x0fnode_signatures\x18\x01 \x01(\v2,.com.hedera.hapi.block.stream.NodeSignaturesH\x00R\x0enodeSignatures\x12!\n" +
	"\vwraps_proof\x18\x02 \x01(\fH\x00R\n" +
	"wrapsProofB\a\n" +
	"\x05proof\"f\n" +
	"\x0eNodeSignatures\x12T\n" +
	"\x0fnode_signatures\x18\x01 \x03(\v2+.com.hedera.hapi.block.stream.NodeSignatureR\x0enodeSignatures\"F\n" +
	"\rNodeSignature\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB'\n" +
	"#com.hedera.hapi.block.stream.protocP\x01b\x06proto3"

var (
	file_chain_of_trust_proof_proto_rawDescOnce sync.Once
	file_chain_of_trust_proof_proto_rawDescData []byte
)

func file_chain_of_trust_proof_proto_rawDescGZIP() []byte {
	file_chain_of_trust_proof_proto_rawDescOnce.Do(func() {
		file_chain_of_trust_proof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_of_trust_proof_proto_rawDesc), len(file_chain_of_trust_proof_proto_rawDesc)))
	})
	return file_chain_of_trust_proof_proto_rawDescData
}

var file_chain_of_trust_proof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chain_of_trust_proof_proto_goTypes = []any{
	(*ChainOfTrustProof)(nil), // 0: com.hedera.hapi.block.stream.ChainOfTrustProof
	(*NodeSignatures)(nil),    // 1: com.hedera.hapi.block.stream.NodeSignatures
	(*NodeSignature)(nil),     // 2: com.hedera.hapi.block.stream.NodeSignature
}
var file_chain_of_trust_proof_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.block.stream.ChainOfTrustProof.node_signatures:type_name -> com.hedera.hapi.block.stream.NodeSignatures
	2, // 1: com.hedera.hapi.block.stream.NodeSignatures.node_signatures:type_name -> com.hedera.hapi.block.stream.NodeSignature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chain_of_trust_proof_proto_init() }
func file_chain_of_trust_proof_proto_init() {
	if File_chain_of_trust_proof_proto != nil {
		return
	}
	file_chain_of_trust_proof_proto_msgTypes[0].OneofWrappers = []any{
		(*ChainOfTrustProof_NodeSignatures)(nil),
		(*ChainOfTrustProof_WrapsProof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_of_trust_proof_proto_rawDesc), len(file_chain_of_trust_proof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_of_trust_proof_proto_goTypes,
		DependencyIndexes: file_chain_of_trust_proof_proto_depIdxs,
		MessageInfos:      file_chain_of_trust_proof_proto_msgTypes,
	}.Build()
	File_chain_of_trust_proof_proto = out.File
	file_chain_of_trust_proof_proto_goTypes = nil
	file_chain_of_trust_proof_proto_depIdxs = nil
}
