//*
// # Consensus Service API
// GRPC service definitions for the Hedera Consensus Service (HCS).
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: consensus_service.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_consensus_service_proto protoreflect.FileDescriptor

const file_consensus_service_proto_rawDesc = "" +
	"\n" +
	"\x17consensus_service.proto\x12\x05proto\x1a\vquery.proto\x1a\x0eresponse.proto\x1a\x1atransaction_response.proto\x1a\x11transaction.proto2\xbf\x02\n" +
	"\x10ConsensusService\x12=\n" +
	"\vcreateTopic\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n" +
	"\vupdateTopic\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n" +
	"\vdeleteTopic\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12?\n" +
	"\rsubmitMessage\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12-\n" +
	"\fgetTopicInfo\x12\f.proto.Query\x1a\x0f.proto.ResponseB(\n" +
	"&com.hederahashgraph.service.proto.javab\x06proto3"

var file_consensus_service_proto_goTypes = []any{
	(*Transaction)(nil),         // 0: proto.Transaction
	(*Query)(nil),               // 1: proto.Query
	(*TransactionResponse)(nil), // 2: proto.TransactionResponse
	(*Response)(nil),            // 3: proto.Response
}
var file_consensus_service_proto_depIdxs = []int32{
	0, // 0: proto.ConsensusService.createTopic:input_type -> proto.Transaction
	0, // 1: proto.ConsensusService.updateTopic:input_type -> proto.Transaction
	0, // 2: proto.ConsensusService.deleteTopic:input_type -> proto.Transaction
	0, // 3: proto.ConsensusService.submitMessage:input_type -> proto.Transaction
	1, // 4: proto.ConsensusService.getTopicInfo:input_type -> proto.Query
	2, // 5: proto.ConsensusService.createTopic:output_type -> proto.TransactionResponse
	2, // 6: proto.ConsensusService.updateTopic:output_type -> proto.TransactionResponse
	2, // 7: proto.ConsensusService.deleteTopic:output_type -> proto.TransactionResponse
	2, // 8: proto.ConsensusService.submitMessage:output_type -> proto.TransactionResponse
	3, // 9: proto.ConsensusService.getTopicInfo:output_type -> proto.Response
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consensus_service_proto_init() }
func file_consensus_service_proto_init() {
	if File_consensus_service_proto != nil {
		return
	}
	file_query_proto_init()
	file_response_proto_init()
	file_transaction_response_proto_init()
	file_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_service_proto_rawDesc), len(file_consensus_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensus_service_proto_goTypes,
		DependencyIndexes: file_consensus_service_proto_depIdxs,
	}.Build()
	File_consensus_service_proto = out.File
	file_consensus_service_proto_goTypes = nil
	file_consensus_service_proto_depIdxs = nil
}
