//*
// # Get contract records
// Deprecated query messages to read all recent contract transaction records.
//
// > REVIEW QUESTION
// >> Can we delete this file and remove the related query entirely?
// >> It appears it hasn't been supported for over 3½ years...
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: contract_get_records.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Deprecated and not supported after release `0.9.0`.
// Request records of all transactions against the given contract in the last 25 hours.
//
// Deprecated: Marked as deprecated in contract_get_records.proto.
type ContractGetRecordsQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Standard information sent with every query operation.<br/>
	// This includes the signed payment and what kind of response is requested
	// (cost, state proof, both, or neither).
	Header *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// A smart contract ID.
	// <p>
	// The network SHALL return information for this smart contract, if successful.
	ContractID    *ContractID `protobuf:"bytes,2,opt,name=contractID,proto3" json:"contractID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractGetRecordsQuery) Reset() {
	*x = ContractGetRecordsQuery{}
	mi := &file_contract_get_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractGetRecordsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractGetRecordsQuery) ProtoMessage() {}

func (x *ContractGetRecordsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_contract_get_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractGetRecordsQuery.ProtoReflect.Descriptor instead.
func (*ContractGetRecordsQuery) Descriptor() ([]byte, []int) {
	return file_contract_get_records_proto_rawDescGZIP(), []int{0}
}

func (x *ContractGetRecordsQuery) GetHeader() *QueryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ContractGetRecordsQuery) GetContractID() *ContractID {
	if x != nil {
		return x.ContractID
	}
	return nil
}

// *
// Deprecated and not supported after release `0.9.0`.
// Response with records of all transactions against the given contract in the last 25 hours.
//
// Deprecated: Marked as deprecated in contract_get_records.proto.
type ContractGetRecordsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The standard response information for queries.<br/>
	// This includes the values requested in the `QueryHeader`
	// (cost, state proof, both, or neither).
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// A smart contract that this response describes.
	ContractID *ContractID `protobuf:"bytes,2,opt,name=contractID,proto3" json:"contractID,omitempty"`
	// *
	// A list of records, each with contractCreateResult or contractCallResult as its body
	Records       []*TransactionRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractGetRecordsResponse) Reset() {
	*x = ContractGetRecordsResponse{}
	mi := &file_contract_get_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractGetRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractGetRecordsResponse) ProtoMessage() {}

func (x *ContractGetRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_get_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractGetRecordsResponse.ProtoReflect.Descriptor instead.
func (*ContractGetRecordsResponse) Descriptor() ([]byte, []int) {
	return file_contract_get_records_proto_rawDescGZIP(), []int{1}
}

func (x *ContractGetRecordsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ContractGetRecordsResponse) GetContractID() *ContractID {
	if x != nil {
		return x.ContractID
	}
	return nil
}

func (x *ContractGetRecordsResponse) GetRecords() []*TransactionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_contract_get_records_proto protoreflect.FileDescriptor

const file_contract_get_records_proto_rawDesc = "" +
	"\n" +
	"\x1acontract_get_records.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x18transaction_record.proto\x1a\x12query_header.proto\x1a\x15response_header.proto\"|\n" +
	"\x17ContractGetRecordsQuery\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.proto.QueryHeaderR\x06header\x121\n" +
	"\n" +
	"contractID\x18\x02 \x01(\v2\x11.proto.ContractIDR\n" +
	"contractID:\x02\x18\x01\"\xb6\x01\n" +
	"\x1aContractGetRecordsResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.proto.ResponseHeaderR\x06header\x121\n" +
	"\n" +
	"contractID\x18\x02 \x01(\v2\x11.proto.ContractIDR\n" +
	"contractID\x122\n" +
	"\arecords\x18\x03 \x03(\v2\x18.proto.TransactionRecordR\arecords:\x02\x18\x01B&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_contract_get_records_proto_rawDescOnce sync.Once
	file_contract_get_records_proto_rawDescData []byte
)

func file_contract_get_records_proto_rawDescGZIP() []byte {
	file_contract_get_records_proto_rawDescOnce.Do(func() {
		file_contract_get_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_get_records_proto_rawDesc), len(file_contract_get_records_proto_rawDesc)))
	})
	return file_contract_get_records_proto_rawDescData
}

var file_contract_get_records_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_get_records_proto_goTypes = []any{
	(*ContractGetRecordsQuery)(nil),    // 0: proto.ContractGetRecordsQuery
	(*ContractGetRecordsResponse)(nil), // 1: proto.ContractGetRecordsResponse
	(*QueryHeader)(nil),                // 2: proto.QueryHeader
	(*ContractID)(nil),                 // 3: proto.ContractID
	(*ResponseHeader)(nil),             // 4: proto.ResponseHeader
	(*TransactionRecord)(nil),          // 5: proto.TransactionRecord
}
var file_contract_get_records_proto_depIdxs = []int32{
	2, // 0: proto.ContractGetRecordsQuery.header:type_name -> proto.QueryHeader
	3, // 1: proto.ContractGetRecordsQuery.contractID:type_name -> proto.ContractID
	4, // 2: proto.ContractGetRecordsResponse.header:type_name -> proto.ResponseHeader
	3, // 3: proto.ContractGetRecordsResponse.contractID:type_name -> proto.ContractID
	5, // 4: proto.ContractGetRecordsResponse.records:type_name -> proto.TransactionRecord
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_contract_get_records_proto_init() }
func file_contract_get_records_proto_init() {
	if File_contract_get_records_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_transaction_record_proto_init()
	file_query_header_proto_init()
	file_response_header_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_get_records_proto_rawDesc), len(file_contract_get_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_get_records_proto_goTypes,
		DependencyIndexes: file_contract_get_records_proto_depIdxs,
		MessageInfos:      file_contract_get_records_proto_msgTypes,
	}.Build()
	File_contract_get_records_proto = out.File
	file_contract_get_records_proto_goTypes = nil
	file_contract_get_records_proto_depIdxs = nil
}
