//*
// # hinTS Key Publication Transaction
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: crs_publication.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A transaction body to publish a node's Common Reference String (CRS) to the network. This is used
// when node wants to update to reach the final CRS for network to use the hinTS protocol
type CrsPublicationTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The party's generated random CRS.
	NewCrs []byte `protobuf:"bytes,1,opt,name=new_crs,json=newCrs,proto3" json:"new_crs,omitempty"`
	// *
	// The party's proof of the CRS update.
	Proof         []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrsPublicationTransactionBody) Reset() {
	*x = CrsPublicationTransactionBody{}
	mi := &file_crs_publication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrsPublicationTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrsPublicationTransactionBody) ProtoMessage() {}

func (x *CrsPublicationTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_crs_publication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrsPublicationTransactionBody.ProtoReflect.Descriptor instead.
func (*CrsPublicationTransactionBody) Descriptor() ([]byte, []int) {
	return file_crs_publication_proto_rawDescGZIP(), []int{0}
}

func (x *CrsPublicationTransactionBody) GetNewCrs() []byte {
	if x != nil {
		return x.NewCrs
	}
	return nil
}

func (x *CrsPublicationTransactionBody) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_crs_publication_proto protoreflect.FileDescriptor

const file_crs_publication_proto_rawDesc = "" +
	"\n" +
	"\x15crs_publication.proto\x12(com.hedera.hapi.services.auxiliary.hints\"N\n" +
	"\x1dCrsPublicationTransactionBody\x12\x17\n" +
	"\anew_crs\x18\x01 \x01(\fR\x06newCrs\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proofB3\n" +
	"/com.hedera.hapi.services.auxiliary.hints.legacyP\x01b\x06proto3"

var (
	file_crs_publication_proto_rawDescOnce sync.Once
	file_crs_publication_proto_rawDescData []byte
)

func file_crs_publication_proto_rawDescGZIP() []byte {
	file_crs_publication_proto_rawDescOnce.Do(func() {
		file_crs_publication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crs_publication_proto_rawDesc), len(file_crs_publication_proto_rawDesc)))
	})
	return file_crs_publication_proto_rawDescData
}

var file_crs_publication_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_crs_publication_proto_goTypes = []any{
	(*CrsPublicationTransactionBody)(nil), // 0: com.hedera.hapi.services.auxiliary.hints.CrsPublicationTransactionBody
}
var file_crs_publication_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crs_publication_proto_init() }
func file_crs_publication_proto_init() {
	if File_crs_publication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crs_publication_proto_rawDesc), len(file_crs_publication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crs_publication_proto_goTypes,
		DependencyIndexes: file_crs_publication_proto_depIdxs,
		MessageInfos:      file_crs_publication_proto_msgTypes,
	}.Build()
	File_crs_publication_proto = out.File
	file_crs_publication_proto_goTypes = nil
	file_crs_publication_proto_depIdxs = nil
}
