//*
// # Core Event Data
// A message that describes the metadata for an event.
//
// The `EventCore` contains a list of the event's parents, as well as the software
// version, an identifier for the node that created this event, the birth round, and
// the creation timestamp for the event.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in [RFC2119](https://www.ietf.org/rfc/rfc2119).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: event_core.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Contains information about an event and its parents.
type EventCore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The creator node identifier.<br/>
	// This SHALL be the unique identifier for the node that created the event.<br/>
	// This SHALL match the ID of the node as it appears in the address book.
	CreatorNodeId int64 `protobuf:"varint,1,opt,name=creator_node_id,json=creatorNodeId,proto3" json:"creator_node_id,omitempty"`
	// *
	// The birth round of the event.<br/>
	// The birth round SHALL be the pending consensus round at the time the event is created.<br/>
	// The pending consensus round SHALL be **one greater** than the latest round to reach consensus.
	BirthRound int64 `protobuf:"varint,2,opt,name=birth_round,json=birthRound,proto3" json:"birth_round,omitempty"`
	// *
	// The wall clock time at which the latest information affecting this event was received by this node.<br/>
	// The information includes: parents, transactions and birth round<br/>
	// If the event is a genesis event, and has no transactions, this value will just be the wall clock time when creating this event.<br/>
	// If the event has a self parent, this timestamp MUST be strictly greater than the `time_created` of the self parent.
	TimeCreated *Timestamp `protobuf:"bytes,3,opt,name=time_created,json=timeCreated,proto3" json:"time_created,omitempty"`
	// *
	// A random number used in the unlikely case that the consensus algorithm gets to a coin vote.<br/>
	// This number SHALL be used to break ties in the consensus algorithm.<br/>
	// The number SHALL be between 0 and the size of the roster (inclusive) for the event's birth round.<br/>
	// For example, if the roster size is 10, the minimum value is 0 and the maximum value is 10.<br/>
	Coin          int64 `protobuf:"varint,5,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCore) Reset() {
	*x = EventCore{}
	mi := &file_event_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCore) ProtoMessage() {}

func (x *EventCore) ProtoReflect() protoreflect.Message {
	mi := &file_event_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCore.ProtoReflect.Descriptor instead.
func (*EventCore) Descriptor() ([]byte, []int) {
	return file_event_core_proto_rawDescGZIP(), []int{0}
}

func (x *EventCore) GetCreatorNodeId() int64 {
	if x != nil {
		return x.CreatorNodeId
	}
	return 0
}

func (x *EventCore) GetBirthRound() int64 {
	if x != nil {
		return x.BirthRound
	}
	return 0
}

func (x *EventCore) GetTimeCreated() *Timestamp {
	if x != nil {
		return x.TimeCreated
	}
	return nil
}

func (x *EventCore) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

var File_event_core_proto protoreflect.FileDescriptor

const file_event_core_proto_rawDesc = "" +
	"\n" +
	"\x10event_core.proto\x12\x1ecom.hedera.hapi.platform.event\x1a\x11basic_types.proto\x1a\x0ftimestamp.proto\"\xa9\x01\n" +
	"\tEventCore\x12&\n" +
	"\x0fcreator_node_id\x18\x01 \x01(\x03R\rcreatorNodeId\x12\x1f\n" +
	"\vbirth_round\x18\x02 \x01(\x03R\n" +
	"birthRound\x123\n" +
	"\ftime_created\x18\x03 \x01(\v2\x10.proto.TimestampR\vtimeCreated\x12\x12\n" +
	"\x04coin\x18\x05 \x01(\x03R\x04coinJ\x04\b\x04\x10\x05J\x04\b\x11\x10\x12B)\n" +
	"%com.hedera.hapi.platform.event.legacyP\x01b\x06proto3"

var (
	file_event_core_proto_rawDescOnce sync.Once
	file_event_core_proto_rawDescData []byte
)

func file_event_core_proto_rawDescGZIP() []byte {
	file_event_core_proto_rawDescOnce.Do(func() {
		file_event_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_core_proto_rawDesc), len(file_event_core_proto_rawDesc)))
	})
	return file_event_core_proto_rawDescData
}

var file_event_core_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_core_proto_goTypes = []any{
	(*EventCore)(nil), // 0: com.hedera.hapi.platform.event.EventCore
	(*Timestamp)(nil), // 1: proto.Timestamp
}
var file_event_core_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.platform.event.EventCore.time_created:type_name -> proto.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_core_proto_init() }
func file_event_core_proto_init() {
	if File_event_core_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_timestamp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_core_proto_rawDesc), len(file_event_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_core_proto_goTypes,
		DependencyIndexes: file_event_core_proto_depIdxs,
		MessageInfos:      file_event_core_proto_msgTypes,
	}.Build()
	File_event_core_proto = out.File
	file_event_core_proto_goTypes = nil
	file_event_core_proto_depIdxs = nil
}
