//*
// # File Create
// Messages to create a new file entry.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: file_create.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Create a new file.
//
// If successful, the new file SHALL contain the (possibly empty) content
// provided in the `contents` field.<br/>
// When the current consensus time exceeds the `expirationTime` value, the
// network SHALL expire the file, and MAY archive the state entry.
//
// #### Signature Requirements
// The HFS manages file authorization in a manner that can be confusing.
// The core element of file authorization is the `keys` field,
// which is a `KeyList`; a list of individual `Key` messages, each of which
// may represent a simple or complex key.<br/>
// The file service transactions treat this list differently.<br/>
// A `fileCreate`, `fileAppend`, or `fileUpdate` MUST have a valid signature
// from _each_ key in the list.<br/>
// A `fileDelete` MUST have a valid signature from _at least one_ key in
// the list. This is different, and allows a file "owned" by many entities
// to be deleted by any one of those entities. A deleted file cannot be
// restored, so it is important to consider this when assigning keys for
// a file.<br/>
// If any of the keys in a `KeyList` are complex, the full requirements of
// each complex key must be met to count as a "valid signature" for that key.
// A complex key structure (i.e. a `ThresholdKey`, or `KeyList`, possibly
// including additional `ThresholdKey` or `KeyList` descendants) may be
// assigned as the sole entry in a file `keys` field to ensure all transactions
// have the same signature requirements.
//
// If the `keys` field is an empty `KeyList`, then the file SHALL be immutable
// and the only transaction permitted to modify that file SHALL be a
// `fileUpdate` transaction with _only_ the `expirationTime` set.
//
// #### Shard and Realm
// The current API ignores shardID and realmID. All files are created in
// shard 0 and realm 0. Future versions of the API may support multiple
// realms and multiple shards.
//
// ### Block Stream Effects
// After the file is created, the FileID for it SHALL be returned in the
// transaction receipt, and SHALL be recorded in the transaction record.
type FileCreateTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// An expiration timestamp.
	// <p>
	// When the network consensus time exceeds this value, the network
	// SHALL expire the file.
	ExpirationTime *Timestamp `protobuf:"bytes,2,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	// *
	// A list of keys that represent file "owners".
	// <p>
	// Every `Key` in this list MUST sign this `fileCreate` transaction, as
	// well as any `fileUpdate` or `fileAppend` that modifies this file.<br/>
	// At least one `Key` in this list MUST sign any `fileDelete` transaction
	// to delete this file.<br/>
	// If this `KeyList` is empty, the file SHALL be created immutable and the
	// only field that may be changed subsequently is the `expirationTime`.
	// An immutable file cannot be deleted except with a `systemDelete`
	// transaction, or by expiration.
	Keys *KeyList `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
	// *
	// A byte array of file content.
	// <p>
	// The file SHALL be created with initial content equal to this field.
	Contents []byte `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
	// *
	// A shard in which this file is created
	ShardID *ShardID `protobuf:"bytes,5,opt,name=shardID,proto3" json:"shardID,omitempty"`
	// *
	// A realm in which this file is created.
	// <p>
	// The shard number for this realm MUST match the value in `shardID`.<br/>
	// Currently, this MUST be `0` for both fields.<br/>
	// If the desired realm is `0.0`, this SHOULD NOT be set.
	RealmID *RealmID `protobuf:"bytes,6,opt,name=realmID,proto3" json:"realmID,omitempty"`
	// *
	// The "create realm" was never enabled, and
	// should not be possible on file creation.<br/>
	// An admin key for a new realm, if one is created.
	// Added deprecated tag 2024-05.
	//
	// Deprecated: Marked as deprecated in file_create.proto.
	NewRealmAdminKey *Key `protobuf:"bytes,7,opt,name=newRealmAdminKey,proto3" json:"newRealmAdminKey,omitempty"`
	// *
	// A short description of this file.
	// <p>
	// This value, if set, MUST NOT exceed `transaction.maxMemoUtf8Bytes`
	// (default 100) bytes when encoded as UTF-8.
	Memo          string `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCreateTransactionBody) Reset() {
	*x = FileCreateTransactionBody{}
	mi := &file_file_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCreateTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreateTransactionBody) ProtoMessage() {}

func (x *FileCreateTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_file_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreateTransactionBody.ProtoReflect.Descriptor instead.
func (*FileCreateTransactionBody) Descriptor() ([]byte, []int) {
	return file_file_create_proto_rawDescGZIP(), []int{0}
}

func (x *FileCreateTransactionBody) GetExpirationTime() *Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *FileCreateTransactionBody) GetKeys() *KeyList {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FileCreateTransactionBody) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *FileCreateTransactionBody) GetShardID() *ShardID {
	if x != nil {
		return x.ShardID
	}
	return nil
}

func (x *FileCreateTransactionBody) GetRealmID() *RealmID {
	if x != nil {
		return x.RealmID
	}
	return nil
}

// Deprecated: Marked as deprecated in file_create.proto.
func (x *FileCreateTransactionBody) GetNewRealmAdminKey() *Key {
	if x != nil {
		return x.NewRealmAdminKey
	}
	return nil
}

func (x *FileCreateTransactionBody) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

var File_file_create_proto protoreflect.FileDescriptor

const file_file_create_proto_rawDesc = "" +
	"\n" +
	"\x11file_create.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x0ftimestamp.proto\"\xb9\x02\n" +
	"\x19FileCreateTransactionBody\x128\n" +
	"\x0eexpirationTime\x18\x02 \x01(\v2\x10.proto.TimestampR\x0eexpirationTime\x12\"\n" +
	"\x04keys\x18\x03 \x01(\v2\x0e.proto.KeyListR\x04keys\x12\x1a\n" +
	"\bcontents\x18\x04 \x01(\fR\bcontents\x12(\n" +
	"\ashardID\x18\x05 \x01(\v2\x0e.proto.ShardIDR\ashardID\x12(\n" +
	"\arealmID\x18\x06 \x01(\v2\x0e.proto.RealmIDR\arealmID\x12:\n" +
	"\x10newRealmAdminKey\x18\a \x01(\v2\n" +
	".proto.KeyB\x02\x18\x01R\x10newRealmAdminKey\x12\x12\n" +
	"\x04memo\x18\b \x01(\tR\x04memoB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_file_create_proto_rawDescOnce sync.Once
	file_file_create_proto_rawDescData []byte
)

func file_file_create_proto_rawDescGZIP() []byte {
	file_file_create_proto_rawDescOnce.Do(func() {
		file_file_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_create_proto_rawDesc), len(file_file_create_proto_rawDesc)))
	})
	return file_file_create_proto_rawDescData
}

var file_file_create_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_file_create_proto_goTypes = []any{
	(*FileCreateTransactionBody)(nil), // 0: proto.FileCreateTransactionBody
	(*Timestamp)(nil),                 // 1: proto.Timestamp
	(*KeyList)(nil),                   // 2: proto.KeyList
	(*ShardID)(nil),                   // 3: proto.ShardID
	(*RealmID)(nil),                   // 4: proto.RealmID
	(*Key)(nil),                       // 5: proto.Key
}
var file_file_create_proto_depIdxs = []int32{
	1, // 0: proto.FileCreateTransactionBody.expirationTime:type_name -> proto.Timestamp
	2, // 1: proto.FileCreateTransactionBody.keys:type_name -> proto.KeyList
	3, // 2: proto.FileCreateTransactionBody.shardID:type_name -> proto.ShardID
	4, // 3: proto.FileCreateTransactionBody.realmID:type_name -> proto.RealmID
	5, // 4: proto.FileCreateTransactionBody.newRealmAdminKey:type_name -> proto.Key
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_file_create_proto_init() }
func file_file_create_proto_init() {
	if File_file_create_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_timestamp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_create_proto_rawDesc), len(file_file_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_create_proto_goTypes,
		DependencyIndexes: file_file_create_proto_depIdxs,
		MessageInfos:      file_file_create_proto_msgTypes,
	}.Build()
	File_file_create_proto = out.File
	file_file_create_proto_goTypes = nil
	file_file_create_proto_depIdxs = nil
}
