//*
// # File Update
// A message to modify the metadata for a file and/or _replace_ the contents.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: file_update.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Update the metadata, and/or replace the content, of a file in the
// Hedera File Service (HFS).
//
// Any field which is not set (i.e. is null) in this message, other than
// `fileID`, SHALL be ignored.<br/>
// If the `keys` list for the identified file is an empty `KeyList`, then
// this message MUST NOT set any field except `expirationTime`.
//
// #### Signature Requirements
// Every `Key` in the `keys` list for the identified file MUST sign this
// transaction, if any field other than `expirationTime` is to be updated.<br/>
// If the `keys` list for the identified file is an empty `KeyList` (because
// this file was previously created or updated to have an empty `KeyList`),
// then the file is considered immutable and this message MUST NOT set any
// field except `expirationTime`.<br/>
// See the [File Service](#FileService) specification for a detailed
// explanation of the signature requirements for all file transactions.
//
// ### Block Stream Effects
// None
type FileUpdateTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A file identifier for the file to update.
	// <p>
	// This field is REQUIRED.
	FileID *FileID `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// *
	// An expiration timestamp.
	// <p>
	// If set, this value MUST be strictly later than the existing
	// `expirationTime` value, or else it will be ignored.<br/>
	// If set, this value SHALL replace the existing `expirationTime`.<br/>
	// If this field is the only field set, then this transaction SHALL NOT
	// require any signature other than the `payer` for the transaction.<br/>
	// When the network consensus time exceeds the then-current
	// `expirationTime`, the network SHALL expire the file.
	ExpirationTime *Timestamp `protobuf:"bytes,2,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	// *
	// The new list of keys that "own" this file.
	// <p>
	// If set, every key in this `KeyList` MUST sign this transaction.<br/>
	// If set, every key in the _previous_ `KeyList` MUST _also_
	// sign this transaction.<br/>
	// If this value is an empty `KeyList`, then the file SHALL be immutable
	// after completion of this transaction.
	Keys *KeyList `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
	// *
	// An array of bytes.
	// <p>
	// This value, if set, SHALL _replace_ the existing file content.
	// If this value is set to an empty byte array, the content of the file
	// SHALL be unchanged.
	Contents []byte `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
	// *
	// A short description of this file.
	// <p>
	// This value, if set, MUST NOT exceed `transaction.maxMemoUtf8Bytes`
	// (default 100) bytes when encoded as UTF-8.
	Memo          *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpdateTransactionBody) Reset() {
	*x = FileUpdateTransactionBody{}
	mi := &file_file_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpdateTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpdateTransactionBody) ProtoMessage() {}

func (x *FileUpdateTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_file_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpdateTransactionBody.ProtoReflect.Descriptor instead.
func (*FileUpdateTransactionBody) Descriptor() ([]byte, []int) {
	return file_file_update_proto_rawDescGZIP(), []int{0}
}

func (x *FileUpdateTransactionBody) GetFileID() *FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

func (x *FileUpdateTransactionBody) GetExpirationTime() *Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *FileUpdateTransactionBody) GetKeys() *KeyList {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FileUpdateTransactionBody) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *FileUpdateTransactionBody) GetMemo() *wrapperspb.StringValue {
	if x != nil {
		return x.Memo
	}
	return nil
}

var File_file_update_proto protoreflect.FileDescriptor

const file_file_update_proto_rawDesc = "" +
	"\n" +
	"\x11file_update.proto\x12\x05proto\x1a\x11basic_types.proto\x1a\x0ftimestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xee\x01\n" +
	"\x19FileUpdateTransactionBody\x12%\n" +
	"\x06fileID\x18\x01 \x01(\v2\r.proto.FileIDR\x06fileID\x128\n" +
	"\x0eexpirationTime\x18\x02 \x01(\v2\x10.proto.TimestampR\x0eexpirationTime\x12\"\n" +
	"\x04keys\x18\x03 \x01(\v2\x0e.proto.KeyListR\x04keys\x12\x1a\n" +
	"\bcontents\x18\x04 \x01(\fR\bcontents\x120\n" +
	"\x04memo\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x04memoB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_file_update_proto_rawDescOnce sync.Once
	file_file_update_proto_rawDescData []byte
)

func file_file_update_proto_rawDescGZIP() []byte {
	file_file_update_proto_rawDescOnce.Do(func() {
		file_file_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_update_proto_rawDesc), len(file_file_update_proto_rawDesc)))
	})
	return file_file_update_proto_rawDescData
}

var file_file_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_file_update_proto_goTypes = []any{
	(*FileUpdateTransactionBody)(nil), // 0: proto.FileUpdateTransactionBody
	(*FileID)(nil),                    // 1: proto.FileID
	(*Timestamp)(nil),                 // 2: proto.Timestamp
	(*KeyList)(nil),                   // 3: proto.KeyList
	(*wrapperspb.StringValue)(nil),    // 4: google.protobuf.StringValue
}
var file_file_update_proto_depIdxs = []int32{
	1, // 0: proto.FileUpdateTransactionBody.fileID:type_name -> proto.FileID
	2, // 1: proto.FileUpdateTransactionBody.expirationTime:type_name -> proto.Timestamp
	3, // 2: proto.FileUpdateTransactionBody.keys:type_name -> proto.KeyList
	4, // 3: proto.FileUpdateTransactionBody.memo:type_name -> google.protobuf.StringValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_file_update_proto_init() }
func file_file_update_proto_init() {
	if File_file_update_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_timestamp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_update_proto_rawDesc), len(file_file_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_update_proto_goTypes,
		DependencyIndexes: file_file_update_proto_depIdxs,
		MessageInfos:      file_file_update_proto_msgTypes,
	}.Build()
	File_file_update_proto = out.File
	file_file_update_proto_goTypes = nil
	file_file_update_proto_depIdxs = nil
}
