//*
// # Proof Key Publication Transaction
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: history_proof_key_publication.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A transaction body to publish a node's history proof key.
type HistoryProofKeyPublicationTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The proof key the submitting node intends to use when
	// contributing signatures for use in proving history
	// belongs to the chain of trust for the ledger id.
	ProofKey      []byte `protobuf:"bytes,1,opt,name=proof_key,json=proofKey,proto3" json:"proof_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryProofKeyPublicationTransactionBody) Reset() {
	*x = HistoryProofKeyPublicationTransactionBody{}
	mi := &file_history_proof_key_publication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryProofKeyPublicationTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryProofKeyPublicationTransactionBody) ProtoMessage() {}

func (x *HistoryProofKeyPublicationTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_history_proof_key_publication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryProofKeyPublicationTransactionBody.ProtoReflect.Descriptor instead.
func (*HistoryProofKeyPublicationTransactionBody) Descriptor() ([]byte, []int) {
	return file_history_proof_key_publication_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryProofKeyPublicationTransactionBody) GetProofKey() []byte {
	if x != nil {
		return x.ProofKey
	}
	return nil
}

var File_history_proof_key_publication_proto protoreflect.FileDescriptor

const file_history_proof_key_publication_proto_rawDesc = "" +
	"\n" +
	"#history_proof_key_publication.proto\x12*com.hedera.hapi.services.auxiliary.history\"H\n" +
	")HistoryProofKeyPublicationTransactionBody\x12\x1b\n" +
	"\tproof_key\x18\x01 \x01(\fR\bproofKeyB5\n" +
	"1com.hedera.hapi.services.auxiliary.history.legacyP\x01b\x06proto3"

var (
	file_history_proof_key_publication_proto_rawDescOnce sync.Once
	file_history_proof_key_publication_proto_rawDescData []byte
)

func file_history_proof_key_publication_proto_rawDescGZIP() []byte {
	file_history_proof_key_publication_proto_rawDescOnce.Do(func() {
		file_history_proof_key_publication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_proof_key_publication_proto_rawDesc), len(file_history_proof_key_publication_proto_rawDesc)))
	})
	return file_history_proof_key_publication_proto_rawDescData
}

var file_history_proof_key_publication_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_history_proof_key_publication_proto_goTypes = []any{
	(*HistoryProofKeyPublicationTransactionBody)(nil), // 0: com.hedera.hapi.services.auxiliary.history.HistoryProofKeyPublicationTransactionBody
}
var file_history_proof_key_publication_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_history_proof_key_publication_proto_init() }
func file_history_proof_key_publication_proto_init() {
	if File_history_proof_key_publication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_proof_key_publication_proto_rawDesc), len(file_history_proof_key_publication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_history_proof_key_publication_proto_goTypes,
		DependencyIndexes: file_history_proof_key_publication_proto_depIdxs,
		MessageInfos:      file_history_proof_key_publication_proto_msgTypes,
	}.Build()
	File_history_proof_key_publication_proto = out.File
	file_history_proof_key_publication_proto_goTypes = nil
	file_history_proof_key_publication_proto_depIdxs = nil
}
