// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: hook_store.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Adds or removes key/value pairs in the storage of an EVM hook.
// Either the hook owner's key, or its admin key, must sign the transaction.
type HookStoreTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The id of the EVM hook whose storage is being updated.
	HookId *HookId `protobuf:"bytes,1,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	// *
	// The updates to the storage of the EVM hook.
	StorageUpdates []*EvmHookStorageUpdate `protobuf:"bytes,2,rep,name=storage_updates,json=storageUpdates,proto3" json:"storage_updates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HookStoreTransactionBody) Reset() {
	*x = HookStoreTransactionBody{}
	mi := &file_hook_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookStoreTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookStoreTransactionBody) ProtoMessage() {}

func (x *HookStoreTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_hook_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookStoreTransactionBody.ProtoReflect.Descriptor instead.
func (*HookStoreTransactionBody) Descriptor() ([]byte, []int) {
	return file_hook_store_proto_rawDescGZIP(), []int{0}
}

func (x *HookStoreTransactionBody) GetHookId() *HookId {
	if x != nil {
		return x.HookId
	}
	return nil
}

func (x *HookStoreTransactionBody) GetStorageUpdates() []*EvmHookStorageUpdate {
	if x != nil {
		return x.StorageUpdates
	}
	return nil
}

var File_hook_store_proto protoreflect.FileDescriptor

const file_hook_store_proto_rawDesc = "" +
	"\n" +
	"\x10hook_store.proto\x12\x1acom.hedera.hapi.node.hooks\x1a\x11basic_types.proto\x1a\x10hook_types.proto\"\x9d\x01\n" +
	"\x18HookStoreTransactionBody\x12&\n" +
	"\ahook_id\x18\x01 \x01(\v2\r.proto.HookIdR\x06hookId\x12Y\n" +
	"\x0fstorage_updates\x18\x02 \x03(\v20.com.hedera.hapi.node.hooks.EvmHookStorageUpdateR\x0estorageUpdatesB%\n" +
	"!com.hedera.hapi.node.hooks.legacyP\x01b\x06proto3"

var (
	file_hook_store_proto_rawDescOnce sync.Once
	file_hook_store_proto_rawDescData []byte
)

func file_hook_store_proto_rawDescGZIP() []byte {
	file_hook_store_proto_rawDescOnce.Do(func() {
		file_hook_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hook_store_proto_rawDesc), len(file_hook_store_proto_rawDesc)))
	})
	return file_hook_store_proto_rawDescData
}

var file_hook_store_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hook_store_proto_goTypes = []any{
	(*HookStoreTransactionBody)(nil), // 0: com.hedera.hapi.node.hooks.HookStoreTransactionBody
	(*HookId)(nil),                   // 1: proto.HookId
	(*EvmHookStorageUpdate)(nil),     // 2: com.hedera.hapi.node.hooks.EvmHookStorageUpdate
}
var file_hook_store_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.node.hooks.HookStoreTransactionBody.hook_id:type_name -> proto.HookId
	2, // 1: com.hedera.hapi.node.hooks.HookStoreTransactionBody.storage_updates:type_name -> com.hedera.hapi.node.hooks.EvmHookStorageUpdate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hook_store_proto_init() }
func file_hook_store_proto_init() {
	if File_hook_store_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_hook_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hook_store_proto_rawDesc), len(file_hook_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hook_store_proto_goTypes,
		DependencyIndexes: file_hook_store_proto_depIdxs,
		MessageInfos:      file_hook_store_proto_msgTypes,
	}.Build()
	File_hook_store_proto = out.File
	file_hook_store_proto_goTypes = nil
	file_hook_store_proto_depIdxs = nil
}
