// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: hook_dispatch.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Dispatches a hook action to an appropriate service.
type HookDispatchTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*HookDispatchTransactionBody_HookIdToDelete
	//	*HookDispatchTransactionBody_Creation
	//	*HookDispatchTransactionBody_Execution
	Action        isHookDispatchTransactionBody_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookDispatchTransactionBody) Reset() {
	*x = HookDispatchTransactionBody{}
	mi := &file_hook_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookDispatchTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookDispatchTransactionBody) ProtoMessage() {}

func (x *HookDispatchTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_hook_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookDispatchTransactionBody.ProtoReflect.Descriptor instead.
func (*HookDispatchTransactionBody) Descriptor() ([]byte, []int) {
	return file_hook_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *HookDispatchTransactionBody) GetAction() isHookDispatchTransactionBody_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *HookDispatchTransactionBody) GetHookIdToDelete() *HookId {
	if x != nil {
		if x, ok := x.Action.(*HookDispatchTransactionBody_HookIdToDelete); ok {
			return x.HookIdToDelete
		}
	}
	return nil
}

func (x *HookDispatchTransactionBody) GetCreation() *HookCreation {
	if x != nil {
		if x, ok := x.Action.(*HookDispatchTransactionBody_Creation); ok {
			return x.Creation
		}
	}
	return nil
}

func (x *HookDispatchTransactionBody) GetExecution() *HookExecution {
	if x != nil {
		if x, ok := x.Action.(*HookDispatchTransactionBody_Execution); ok {
			return x.Execution
		}
	}
	return nil
}

type isHookDispatchTransactionBody_Action interface {
	isHookDispatchTransactionBody_Action()
}

type HookDispatchTransactionBody_HookIdToDelete struct {
	// *
	// The id of the hook to delete.
	HookIdToDelete *HookId `protobuf:"bytes,1,opt,name=hook_id_to_delete,json=hookIdToDelete,proto3,oneof"`
}

type HookDispatchTransactionBody_Creation struct {
	// *
	// Creation details for a new hook.
	Creation *HookCreation `protobuf:"bytes,2,opt,name=creation,proto3,oneof"`
}

type HookDispatchTransactionBody_Execution struct {
	// *
	// Execution details of an existing hook.
	Execution *HookExecution `protobuf:"bytes,3,opt,name=execution,proto3,oneof"`
}

func (*HookDispatchTransactionBody_HookIdToDelete) isHookDispatchTransactionBody_Action() {}

func (*HookDispatchTransactionBody_Creation) isHookDispatchTransactionBody_Action() {}

func (*HookDispatchTransactionBody_Execution) isHookDispatchTransactionBody_Action() {}

// *
// Details the execution of a hook.
type HookExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The id of the hook's entity.
	HookEntityId *HookEntityId `protobuf:"bytes,1,opt,name=hook_entity_id,json=hookEntityId,proto3" json:"hook_entity_id,omitempty"`
	// *
	// The details of the call, including which hook id to call.
	Call          *HookCall `protobuf:"bytes,2,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookExecution) Reset() {
	*x = HookExecution{}
	mi := &file_hook_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookExecution) ProtoMessage() {}

func (x *HookExecution) ProtoReflect() protoreflect.Message {
	mi := &file_hook_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookExecution.ProtoReflect.Descriptor instead.
func (*HookExecution) Descriptor() ([]byte, []int) {
	return file_hook_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *HookExecution) GetHookEntityId() *HookEntityId {
	if x != nil {
		return x.HookEntityId
	}
	return nil
}

func (x *HookExecution) GetCall() *HookCall {
	if x != nil {
		return x.Call
	}
	return nil
}

var File_hook_dispatch_proto protoreflect.FileDescriptor

const file_hook_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x13hook_dispatch.proto\x12\x1acom.hedera.hapi.node.hooks\x1a\x11basic_types.proto\x1a\x10hook_types.proto\"\xf6\x01\n" +
	"\x1bHookDispatchTransactionBody\x12:\n" +
	"\x11hook_id_to_delete\x18\x01 \x01(\v2\r.proto.HookIdH\x00R\x0ehookIdToDelete\x12F\n" +
	"\bcreation\x18\x02 \x01(\v2(.com.hedera.hapi.node.hooks.HookCreationH\x00R\bcreation\x12I\n" +
	"\texecution\x18\x03 \x01(\v2).com.hedera.hapi.node.hooks.HookExecutionH\x00R\texecutionB\b\n" +
	"\x06action\"o\n" +
	"\rHookExecution\x129\n" +
	"\x0ehook_entity_id\x18\x01 \x01(\v2\x13.proto.HookEntityIdR\fhookEntityId\x12#\n" +
	"\x04call\x18\x02 \x01(\v2\x0f.proto.HookCallR\x04callB%\n" +
	"!com.hedera.hapi.node.hooks.legacyP\x01b\x06proto3"

var (
	file_hook_dispatch_proto_rawDescOnce sync.Once
	file_hook_dispatch_proto_rawDescData []byte
)

func file_hook_dispatch_proto_rawDescGZIP() []byte {
	file_hook_dispatch_proto_rawDescOnce.Do(func() {
		file_hook_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hook_dispatch_proto_rawDesc), len(file_hook_dispatch_proto_rawDesc)))
	})
	return file_hook_dispatch_proto_rawDescData
}

var file_hook_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hook_dispatch_proto_goTypes = []any{
	(*HookDispatchTransactionBody)(nil), // 0: com.hedera.hapi.node.hooks.HookDispatchTransactionBody
	(*HookExecution)(nil),               // 1: com.hedera.hapi.node.hooks.HookExecution
	(*HookId)(nil),                      // 2: proto.HookId
	(*HookCreation)(nil),                // 3: com.hedera.hapi.node.hooks.HookCreation
	(*HookEntityId)(nil),                // 4: proto.HookEntityId
	(*HookCall)(nil),                    // 5: proto.HookCall
}
var file_hook_dispatch_proto_depIdxs = []int32{
	2, // 0: com.hedera.hapi.node.hooks.HookDispatchTransactionBody.hook_id_to_delete:type_name -> proto.HookId
	3, // 1: com.hedera.hapi.node.hooks.HookDispatchTransactionBody.creation:type_name -> com.hedera.hapi.node.hooks.HookCreation
	1, // 2: com.hedera.hapi.node.hooks.HookDispatchTransactionBody.execution:type_name -> com.hedera.hapi.node.hooks.HookExecution
	4, // 3: com.hedera.hapi.node.hooks.HookExecution.hook_entity_id:type_name -> proto.HookEntityId
	5, // 4: com.hedera.hapi.node.hooks.HookExecution.call:type_name -> proto.HookCall
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hook_dispatch_proto_init() }
func file_hook_dispatch_proto_init() {
	if File_hook_dispatch_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_hook_types_proto_init()
	file_hook_dispatch_proto_msgTypes[0].OneofWrappers = []any{
		(*HookDispatchTransactionBody_HookIdToDelete)(nil),
		(*HookDispatchTransactionBody_Creation)(nil),
		(*HookDispatchTransactionBody_Execution)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hook_dispatch_proto_rawDesc), len(file_hook_dispatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hook_dispatch_proto_goTypes,
		DependencyIndexes: file_hook_dispatch_proto_depIdxs,
		MessageInfos:      file_hook_dispatch_proto_msgTypes,
	}.Build()
	File_hook_dispatch_proto = out.File
	file_hook_dispatch_proto_goTypes = nil
	file_hook_dispatch_proto_depIdxs = nil
}
