//*
// # Migration Root Hash Vote Transaction
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.rfc-editor.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: migration_root_hash_vote.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A transaction body to publish a node's vote for wrapped record migration state.
type MigrationRootHashVoteTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The previous wrapped record block root hash from startup migration.
	PreviousWrappedRecordBlockRootHash []byte `protobuf:"bytes,1,opt,name=previous_wrapped_record_block_root_hash,json=previousWrappedRecordBlockRootHash,proto3" json:"previous_wrapped_record_block_root_hash,omitempty"`
	// *
	// Intermediate hashing state for wrapped previous block roots.
	WrappedIntermediatePreviousBlockRootHashes [][]byte `protobuf:"bytes,2,rep,name=wrapped_intermediate_previous_block_root_hashes,json=wrappedIntermediatePreviousBlockRootHashes,proto3" json:"wrapped_intermediate_previous_block_root_hashes,omitempty"`
	// *
	// Leaf count of the wrapped previous block roots hasher.
	WrappedIntermediateBlockRootsLeafCount uint64 `protobuf:"varint,3,opt,name=wrapped_intermediate_block_roots_leaf_count,json=wrappedIntermediateBlockRootsLeafCount,proto3" json:"wrapped_intermediate_block_roots_leaf_count,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *MigrationRootHashVoteTransactionBody) Reset() {
	*x = MigrationRootHashVoteTransactionBody{}
	mi := &file_migration_root_hash_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRootHashVoteTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRootHashVoteTransactionBody) ProtoMessage() {}

func (x *MigrationRootHashVoteTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_migration_root_hash_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRootHashVoteTransactionBody.ProtoReflect.Descriptor instead.
func (*MigrationRootHashVoteTransactionBody) Descriptor() ([]byte, []int) {
	return file_migration_root_hash_vote_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationRootHashVoteTransactionBody) GetPreviousWrappedRecordBlockRootHash() []byte {
	if x != nil {
		return x.PreviousWrappedRecordBlockRootHash
	}
	return nil
}

func (x *MigrationRootHashVoteTransactionBody) GetWrappedIntermediatePreviousBlockRootHashes() [][]byte {
	if x != nil {
		return x.WrappedIntermediatePreviousBlockRootHashes
	}
	return nil
}

func (x *MigrationRootHashVoteTransactionBody) GetWrappedIntermediateBlockRootsLeafCount() uint64 {
	if x != nil {
		return x.WrappedIntermediateBlockRootsLeafCount
	}
	return 0
}

var File_migration_root_hash_vote_proto protoreflect.FileDescriptor

const file_migration_root_hash_vote_proto_rawDesc = "" +
	"\n" +
	"\x1emigration_root_hash_vote.proto\x12/com.hedera.hapi.services.auxiliary.blockrecords\"\xbd\x02\n" +
	"$MigrationRootHashVoteTransactionBody\x12S\n" +
	"'previous_wrapped_record_block_root_hash\x18\x01 \x01(\fR\"previousWrappedRecordBlockRootHash\x12c\n" +
	"/wrapped_intermediate_previous_block_root_hashes\x18\x02 \x03(\fR*wrappedIntermediatePreviousBlockRootHashes\x12[\n" +
	"+wrapped_intermediate_block_roots_leaf_count\x18\x03 \x01(\x04R&wrappedIntermediateBlockRootsLeafCountB:\n" +
	"6com.hedera.hapi.services.auxiliary.blockrecords.legacyP\x01b\x06proto3"

var (
	file_migration_root_hash_vote_proto_rawDescOnce sync.Once
	file_migration_root_hash_vote_proto_rawDescData []byte
)

func file_migration_root_hash_vote_proto_rawDescGZIP() []byte {
	file_migration_root_hash_vote_proto_rawDescOnce.Do(func() {
		file_migration_root_hash_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_root_hash_vote_proto_rawDesc), len(file_migration_root_hash_vote_proto_rawDesc)))
	})
	return file_migration_root_hash_vote_proto_rawDescData
}

var file_migration_root_hash_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_migration_root_hash_vote_proto_goTypes = []any{
	(*MigrationRootHashVoteTransactionBody)(nil), // 0: com.hedera.hapi.services.auxiliary.blockrecords.MigrationRootHashVoteTransactionBody
}
var file_migration_root_hash_vote_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_migration_root_hash_vote_proto_init() }
func file_migration_root_hash_vote_proto_init() {
	if File_migration_root_hash_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_root_hash_vote_proto_rawDesc), len(file_migration_root_hash_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migration_root_hash_vote_proto_goTypes,
		DependencyIndexes: file_migration_root_hash_vote_proto_depIdxs,
		MessageInfos:      file_migration_root_hash_vote_proto_msgTypes,
	}.Build()
	File_migration_root_hash_vote_proto = out.File
	file_migration_root_hash_vote_proto_goTypes = nil
	file_migration_root_hash_vote_proto_depIdxs = nil
}
