// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: node_delete.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A transaction body to delete a node from the network address book.
//
//   - A `NodeDeleteTransactionBody` MUST be signed by one of those keys:
//     adminKey, treasure account (2) key, systemAdmin(50) key, or
//     addressBookAdmin(55) key.
//   - Upon success, the address book entry SHALL enter a "pending delete"
//     state.
//   - All address book entries pending deletion SHALL be removed from the
//     active network configuration during the next `freeze` transaction with
//     the field `freeze_type` set to `PREPARE_UPGRADE`.<br/>
//   - A deleted address book node SHALL be removed entirely from network state.
//   - A deleted address book node identifier SHALL NOT be reused.
//
// ### Block Stream Effects
// None.
type NodeDeleteTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A consensus node identifier in the network state.
	// <p>
	// The node identified MUST exist in the network address book.<br/>
	// The node identified MUST NOT be deleted.<br/>
	// This value is REQUIRED.
	NodeId        uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDeleteTransactionBody) Reset() {
	*x = NodeDeleteTransactionBody{}
	mi := &file_node_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDeleteTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeleteTransactionBody) ProtoMessage() {}

func (x *NodeDeleteTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_node_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeleteTransactionBody.ProtoReflect.Descriptor instead.
func (*NodeDeleteTransactionBody) Descriptor() ([]byte, []int) {
	return file_node_delete_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDeleteTransactionBody) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

var File_node_delete_proto protoreflect.FileDescriptor

const file_node_delete_proto_rawDesc = "" +
	"\n" +
	"\x11node_delete.proto\x12 com.hedera.hapi.node.addressbook\"4\n" +
	"\x19NodeDeleteTransactionBody\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeIdB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_node_delete_proto_rawDescOnce sync.Once
	file_node_delete_proto_rawDescData []byte
)

func file_node_delete_proto_rawDescGZIP() []byte {
	file_node_delete_proto_rawDescOnce.Do(func() {
		file_node_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_delete_proto_rawDesc), len(file_node_delete_proto_rawDesc)))
	})
	return file_node_delete_proto_rawDescData
}

var file_node_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_delete_proto_goTypes = []any{
	(*NodeDeleteTransactionBody)(nil), // 0: com.hedera.hapi.node.addressbook.NodeDeleteTransactionBody
}
var file_node_delete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_delete_proto_init() }
func file_node_delete_proto_init() {
	if File_node_delete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_delete_proto_rawDesc), len(file_node_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_delete_proto_goTypes,
		DependencyIndexes: file_node_delete_proto_depIdxs,
		MessageInfos:      file_node_delete_proto_msgTypes,
	}.Build()
	File_node_delete_proto = out.File
	file_node_delete_proto_goTypes = nil
	file_node_delete_proto_depIdxs = nil
}
