//*
// # Node Payments
// This is a Singleton that stores node fees accumulated in the current staking period.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in [RFC2119](https://www.ietf.org/rfc/rfc2119)
// and clarified in [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: node_payments.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A singleton state object that accumulates node fees for distribution<br/>
// This is used to record the total amount of fees due to each node for distribution in current staking period
type NodePayments struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The time when the last node fees were distributed
	LastNodeFeeDistributionTime *Timestamp `protobuf:"bytes,1,opt,name=last_node_fee_distribution_time,json=lastNodeFeeDistributionTime,proto3" json:"last_node_fee_distribution_time,omitempty"`
	// *
	// A list of node account id to the total amount of fees due to each node in the current staking period
	Payments      []*NodePayment `protobuf:"bytes,2,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePayments) Reset() {
	*x = NodePayments{}
	mi := &file_node_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePayments) ProtoMessage() {}

func (x *NodePayments) ProtoReflect() protoreflect.Message {
	mi := &file_node_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePayments.ProtoReflect.Descriptor instead.
func (*NodePayments) Descriptor() ([]byte, []int) {
	return file_node_payments_proto_rawDescGZIP(), []int{0}
}

func (x *NodePayments) GetLastNodeFeeDistributionTime() *Timestamp {
	if x != nil {
		return x.LastNodeFeeDistributionTime
	}
	return nil
}

func (x *NodePayments) GetPayments() []*NodePayment {
	if x != nil {
		return x.Payments
	}
	return nil
}

// *
// A record of the total amount of fees due to a node
type NodePayment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The node account id
	NodeAccountId *AccountID `protobuf:"bytes,1,opt,name=node_account_id,json=nodeAccountId,proto3" json:"node_account_id,omitempty"`
	// *
	// The total amount of fees due to the node in tinybars
	Fees          uint64 `protobuf:"varint,2,opt,name=fees,proto3" json:"fees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePayment) Reset() {
	*x = NodePayment{}
	mi := &file_node_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePayment) ProtoMessage() {}

func (x *NodePayment) ProtoReflect() protoreflect.Message {
	mi := &file_node_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePayment.ProtoReflect.Descriptor instead.
func (*NodePayment) Descriptor() ([]byte, []int) {
	return file_node_payments_proto_rawDescGZIP(), []int{1}
}

func (x *NodePayment) GetNodeAccountId() *AccountID {
	if x != nil {
		return x.NodeAccountId
	}
	return nil
}

func (x *NodePayment) GetFees() uint64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

var File_node_payments_proto protoreflect.FileDescriptor

const file_node_payments_proto_rawDesc = "" +
	"\n" +
	"\x13node_payments.proto\x12 com.hedera.hapi.node.state.token\x1a\x0ftimestamp.proto\x1a\x11basic_types.proto\"\xb1\x01\n" +
	"\fNodePayments\x12V\n" +
	"\x1flast_node_fee_distribution_time\x18\x01 \x01(\v2\x10.proto.TimestampR\x1blastNodeFeeDistributionTime\x12I\n" +
	"\bpayments\x18\x02 \x03(\v2-.com.hedera.hapi.node.state.token.NodePaymentR\bpayments\"[\n" +
	"\vNodePayment\x128\n" +
	"\x0fnode_account_id\x18\x01 \x01(\v2\x10.proto.AccountIDR\rnodeAccountId\x12\x12\n" +
	"\x04fees\x18\x02 \x01(\x04R\x04feesB+\n" +
	"'com.hedera.hapi.node.state.token.legacyP\x01b\x06proto3"

var (
	file_node_payments_proto_rawDescOnce sync.Once
	file_node_payments_proto_rawDescData []byte
)

func file_node_payments_proto_rawDescGZIP() []byte {
	file_node_payments_proto_rawDescOnce.Do(func() {
		file_node_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_payments_proto_rawDesc), len(file_node_payments_proto_rawDesc)))
	})
	return file_node_payments_proto_rawDescData
}

var file_node_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_payments_proto_goTypes = []any{
	(*NodePayments)(nil), // 0: com.hedera.hapi.node.state.token.NodePayments
	(*NodePayment)(nil),  // 1: com.hedera.hapi.node.state.token.NodePayment
	(*Timestamp)(nil),    // 2: proto.Timestamp
	(*AccountID)(nil),    // 3: proto.AccountID
}
var file_node_payments_proto_depIdxs = []int32{
	2, // 0: com.hedera.hapi.node.state.token.NodePayments.last_node_fee_distribution_time:type_name -> proto.Timestamp
	1, // 1: com.hedera.hapi.node.state.token.NodePayments.payments:type_name -> com.hedera.hapi.node.state.token.NodePayment
	3, // 2: com.hedera.hapi.node.state.token.NodePayment.node_account_id:type_name -> proto.AccountID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_node_payments_proto_init() }
func file_node_payments_proto_init() {
	if File_node_payments_proto != nil {
		return
	}
	file_timestamp_proto_init()
	file_basic_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_payments_proto_rawDesc), len(file_node_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_payments_proto_goTypes,
		DependencyIndexes: file_node_payments_proto_depIdxs,
		MessageInfos:      file_node_payments_proto_msgTypes,
	}.Build()
	File_node_payments_proto = out.File
	file_node_payments_proto_goTypes = nil
	file_node_payments_proto_depIdxs = nil
}
