// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: node.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A single address book node in the network state.
//
// Each node in the network address book SHALL represent a single actual
// consensus node that is eligible to participate in network consensus.
//
// Address book nodes SHALL NOT be _globally_ uniquely identified. A given node
// is only valid within a single realm and shard combination, so the identifier
// for a network node SHALL only be unique within a single realm and shard
// combination.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A consensus node identifier.
	// <p>
	// Node identifiers SHALL be globally unique for a given ledger.
	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// *
	// An account identifier.
	// <p>
	// This account SHALL be owned by the entity responsible for the node.<br/>
	// This account SHALL be charged transaction fees for any transactions
	// that are submitted to the network by this node and
	// fail due diligence checks.<br/>
	// This account SHALL be paid the node portion of transaction fees
	// for transactions submitted by this node.
	AccountId *AccountID `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// *
	// A short description of the node.
	// <p>
	// This value, if set, MUST NOT exceed `transaction.maxMemoUtf8Bytes`
	// (default 100) bytes when encoded as UTF-8.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// *
	// A list of service endpoints for gossip.
	// <p>
	// These endpoints SHALL represent the published endpoints to which other
	// consensus nodes may _gossip_ transactions.<br/>
	// If the network configuration value `gossipFqdnRestricted` is set, then
	// all endpoints in this list SHALL supply only IP address.<br/>
	// If the network configuration value `gossipFqdnRestricted` is _not_ set,
	// then endpoints in this list MAY supply either IP address or FQDN, but
	// SHALL NOT supply both values for the same endpoint.<br/>
	// This list SHALL NOT be empty.<br/>
	// This list SHALL NOT contain more than `10` entries.<br/>
	// The first two entries in this list SHALL be the endpoints published to
	// all consensus nodes.<br/>
	// All other entries SHALL be reserved for future use.
	GossipEndpoint []*ServiceEndpoint `protobuf:"bytes,4,rep,name=gossip_endpoint,json=gossipEndpoint,proto3" json:"gossip_endpoint,omitempty"`
	// *
	// A list of service endpoints for client calls.
	// <p>
	// These endpoints SHALL represent the published endpoints to which clients
	// may submit transactions.<br/>
	// These endpoints SHALL specify a port.<br/>
	// Endpoints in this list MAY supply either IP address or FQDN, but SHALL
	// NOT supply both values for the same endpoint.<br/>
	// This list SHALL NOT be empty.<br/>
	// This list SHALL NOT contain more than `8` entries.
	ServiceEndpoint []*ServiceEndpoint `protobuf:"bytes,5,rep,name=service_endpoint,json=serviceEndpoint,proto3" json:"service_endpoint,omitempty"`
	// *
	// A certificate used to sign gossip events.
	// <p>
	// This value SHALL be a certificate of a type permitted for gossip
	// signatures.<br/>
	// This value SHALL be the DER encoding of the certificate presented.<br/>
	// This field is REQUIRED and MUST NOT be empty.
	GossipCaCertificate []byte `protobuf:"bytes,6,opt,name=gossip_ca_certificate,json=gossipCaCertificate,proto3" json:"gossip_ca_certificate,omitempty"`
	// *
	// A hash of the node gRPC certificate.
	// <p>
	// This value MAY be used to verify the certificate presented by the node
	// during TLS negotiation for gRPC.<br/>
	// This value SHALL be a SHA-384 hash.<br/>
	// The TLS certificate to be hashed SHALL first be in PEM format and SHALL
	// be encoded with UTF-8 NFKD encoding to a stream of bytes provided to
	// the hash algorithm.<br/>
	// This field is OPTIONAL.
	GrpcCertificateHash []byte `protobuf:"bytes,7,opt,name=grpc_certificate_hash,json=grpcCertificateHash,proto3" json:"grpc_certificate_hash,omitempty"`
	// *
	// A consensus weight.
	// <p>
	// Each node SHALL have a weight in consensus calculations.<br/>
	// The consensus weight of a node SHALL be calculated based on the amount
	// of HBAR staked to that node.<br/>
	// Consensus SHALL be calculated based on agreement of greater than `2/3`
	// of the total `weight` value of all nodes on the network.
	// <p>
	// This field is deprecated and SHALL NOT be used when RosterLifecycle
	// is enabled.
	//
	// Deprecated: Marked as deprecated in node.proto.
	Weight uint64 `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	// *
	// A flag indicating this node is deleted.
	// <p>
	// If this field is set, then this node SHALL NOT be included in the next
	// update of the network address book.<br/>
	// If this field is set, then this node SHALL be immutable and SHALL NOT
	// be modified.<br/>
	// If this field is set, then any `nodeUpdate` transaction to modify this
	// node SHALL fail.
	Deleted bool `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// *
	// An administrative key controlled by the node operator.
	// <p>
	// This key MUST sign each transaction to update this node.<br/>
	// This field MUST contain a valid `Key` value.<br/>
	// This field is REQUIRED and MUST NOT be set to an empty `KeyList`.
	AdminKey *Key `protobuf:"bytes,10,opt,name=admin_key,json=adminKey,proto3" json:"admin_key,omitempty"`
	// *
	// A flag indicating this node declines node rewards distributed at
	// the end of staking period.
	// <p>
	// If this field is set, then this node SHALL NOT receive any node rewards
	// distributed at the end of the staking period.
	DeclineReward bool `protobuf:"varint,11,opt,name=decline_reward,json=declineReward,proto3" json:"decline_reward,omitempty"`
	// *
	// A web proxy for gRPC from non-gRPC clients.
	// <p>
	// This endpoint SHALL be a Fully Qualified Domain Name (FQDN) using the HTTPS
	// protocol, and SHALL support gRPC-Web for use by browser-based clients.<br/>
	// This endpoint MUST be signed by a trusted certificate authority.<br/>
	// This endpoint MUST use a valid port and SHALL be reachable over TLS.<br/>
	// This field MAY be omitted if the node does not support gRPC-Web access.<br/>
	// This field MUST be updated if the gRPC-Web endpoint changes.<br/>
	// This field SHALL enable frontend clients to avoid hard-coded proxy endpoints.
	GrpcProxyEndpoint *ServiceEndpoint `protobuf:"bytes,12,opt,name=grpc_proxy_endpoint,json=grpcProxyEndpoint,proto3" json:"grpc_proxy_endpoint,omitempty"`
	// *
	// A list of registered nodes operated by the same entity as this node.<br/>
	// This value may contain a list of "registered nodes" (as described in
	// HIP-1137) that are operated by the same entity that operates this
	// consensus node.
	// <p>
	// This field is OPTIONAL and MAY be empty.<br/>
	// This field MUST NOT contain more than twenty(20) entries.<br/>
	// Every entry in this list MUST be a valid `registered_node_id` for a
	// current registered node.
	AssociatedRegisteredNode []uint64 `protobuf:"varint,13,rep,packed,name=associated_registered_node,json=associatedRegisteredNode,proto3" json:"associated_registered_node,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Node) GetAccountId() *AccountID {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Node) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Node) GetGossipEndpoint() []*ServiceEndpoint {
	if x != nil {
		return x.GossipEndpoint
	}
	return nil
}

func (x *Node) GetServiceEndpoint() []*ServiceEndpoint {
	if x != nil {
		return x.ServiceEndpoint
	}
	return nil
}

func (x *Node) GetGossipCaCertificate() []byte {
	if x != nil {
		return x.GossipCaCertificate
	}
	return nil
}

func (x *Node) GetGrpcCertificateHash() []byte {
	if x != nil {
		return x.GrpcCertificateHash
	}
	return nil
}

// Deprecated: Marked as deprecated in node.proto.
func (x *Node) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Node) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Node) GetAdminKey() *Key {
	if x != nil {
		return x.AdminKey
	}
	return nil
}

func (x *Node) GetDeclineReward() bool {
	if x != nil {
		return x.DeclineReward
	}
	return false
}

func (x *Node) GetGrpcProxyEndpoint() *ServiceEndpoint {
	if x != nil {
		return x.GrpcProxyEndpoint
	}
	return nil
}

func (x *Node) GetAssociatedRegisteredNode() []uint64 {
	if x != nil {
		return x.AssociatedRegisteredNode
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12&com.hedera.hapi.node.state.addressbook\x1a\x11basic_types.proto\"\xea\x04\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12/\n" +
	"\n" +
	"account_id\x18\x02 \x01(\v2\x10.proto.AccountIDR\taccountId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\x0fgossip_endpoint\x18\x04 \x03(\v2\x16.proto.ServiceEndpointR\x0egossipEndpoint\x12A\n" +
	"\x10service_endpoint\x18\x05 \x03(\v2\x16.proto.ServiceEndpointR\x0fserviceEndpoint\x122\n" +
	"\x15gossip_ca_certificate\x18\x06 \x01(\fR\x13gossipCaCertificate\x122\n" +
	"\x15grpc_certificate_hash\x18\a \x01(\fR\x13grpcCertificateHash\x12\x1a\n" +
	"\x06weight\x18\b \x01(\x04B\x02\x18\x01R\x06weight\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\x12'\n" +
	"\tadmin_key\x18\n" +
	" \x01(\v2\n" +
	".proto.KeyR\badminKey\x12%\n" +
	"\x0edecline_reward\x18\v \x01(\bR\rdeclineReward\x12F\n" +
	"\x13grpc_proxy_endpoint\x18\f \x01(\v2\x16.proto.ServiceEndpointR\x11grpcProxyEndpoint\x12<\n" +
	"\x1aassociated_registered_node\x18\r \x03(\x04R\x18associatedRegisteredNodeB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_proto_goTypes = []any{
	(*Node)(nil),            // 0: com.hedera.hapi.node.state.addressbook.Node
	(*AccountID)(nil),       // 1: proto.AccountID
	(*ServiceEndpoint)(nil), // 2: proto.ServiceEndpoint
	(*Key)(nil),             // 3: proto.Key
}
var file_node_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.node.state.addressbook.Node.account_id:type_name -> proto.AccountID
	2, // 1: com.hedera.hapi.node.state.addressbook.Node.gossip_endpoint:type_name -> proto.ServiceEndpoint
	2, // 2: com.hedera.hapi.node.state.addressbook.Node.service_endpoint:type_name -> proto.ServiceEndpoint
	3, // 3: com.hedera.hapi.node.state.addressbook.Node.admin_key:type_name -> proto.Key
	2, // 4: com.hedera.hapi.node.state.addressbook.Node.grpc_proxy_endpoint:type_name -> proto.ServiceEndpoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_basic_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
