// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: registered_node_update.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A transaction body to update an existing registered node in the network
// address book.
//
// This transaction, once complete, SHALL modify the identified registered
// node state as requested.
//
// ### Block Stream Effects
// None.
type RegisteredNodeUpdateTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A registered node identifier in the network state.
	// <p>
	// The node identified MUST exist in the registered address book.<br/>
	// The node identified MUST NOT be deleted.<br/>
	// This value is REQUIRED.
	// <p>
	// A given value for `registered_node_id` SHALL be unique within a given
	// shard or realm.<br/>
	// A given value for `registered_node_id` SHALL NOT be reused, even if the
	// corresponding entry is deleted.
	RegisteredNodeId uint64 `protobuf:"varint,1,opt,name=registered_node_id,json=registeredNodeId,proto3" json:"registered_node_id,omitempty"`
	// *
	// An administrative key controlled by the node operator.
	// <p>
	// This field is OPTIONAL.<br/>
	// If set, this key MUST sign this transaction.<br/>
	// If set, this key MUST sign each subsequent transaction to
	// update this node.<br/>
	// If set, this field MUST contain a valid `Key` value.<br/>
	// If set, this field MUST NOT be set to an empty `KeyList`.<br/>
	// It is RECOMMENDED that this key be composed of one or more unique public
	// keys that are not associated with any network account.<br/>
	// This key MAY be a complex key containing `KeyList` or `ThresholdKey`
	// elements, but SHOULD NOT be a contract ID key.
	AdminKey *Key `protobuf:"bytes,2,opt,name=admin_key,json=adminKey,proto3" json:"admin_key,omitempty"`
	// *
	// A short description of the node.
	// <p>
	// This field is OPTIONAL.<br/>
	// This value, if set, MUST NOT exceed 100 bytes when encoded as UTF-8.<br/>
	// If set, this value SHALL replace the previous value.
	Description *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// *
	// A list of service endpoints for client calls.
	// <p>
	// This field is OPTIONAL.<br/>
	// These endpoints SHALL represent the published endpoints to which
	// clients may submit requests.<br/>
	// Endpoints in this list MAY supply either IP address or FQDN, but MUST
	// NOT supply both values for the same endpoint.<br/>
	// One Registered Node MAY expose endpoints for multiple service types.<br/>
	// If set, this list MUST NOT be empty.<br/>
	// If set, this list MUST NOT contain more than `50` entries.<br/>
	// If set, this list SHALL _replace_ the previous list.
	ServiceEndpoint []*RegisteredServiceEndpoint `protobuf:"bytes,4,rep,name=service_endpoint,json=serviceEndpoint,proto3" json:"service_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisteredNodeUpdateTransactionBody) Reset() {
	*x = RegisteredNodeUpdateTransactionBody{}
	mi := &file_registered_node_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredNodeUpdateTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredNodeUpdateTransactionBody) ProtoMessage() {}

func (x *RegisteredNodeUpdateTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_registered_node_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredNodeUpdateTransactionBody.ProtoReflect.Descriptor instead.
func (*RegisteredNodeUpdateTransactionBody) Descriptor() ([]byte, []int) {
	return file_registered_node_update_proto_rawDescGZIP(), []int{0}
}

func (x *RegisteredNodeUpdateTransactionBody) GetRegisteredNodeId() uint64 {
	if x != nil {
		return x.RegisteredNodeId
	}
	return 0
}

func (x *RegisteredNodeUpdateTransactionBody) GetAdminKey() *Key {
	if x != nil {
		return x.AdminKey
	}
	return nil
}

func (x *RegisteredNodeUpdateTransactionBody) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *RegisteredNodeUpdateTransactionBody) GetServiceEndpoint() []*RegisteredServiceEndpoint {
	if x != nil {
		return x.ServiceEndpoint
	}
	return nil
}

var File_registered_node_update_proto protoreflect.FileDescriptor

const file_registered_node_update_proto_rawDesc = "" +
	"\n" +
	"\x1cregistered_node_update.proto\x12 com.hedera.hapi.node.addressbook\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11basic_types.proto\x1a!registered_service_endpoint.proto\"\xa4\x02\n" +
	"#RegisteredNodeUpdateTransactionBody\x12,\n" +
	"\x12registered_node_id\x18\x01 \x01(\x04R\x10registeredNodeId\x12'\n" +
	"\tadmin_key\x18\x02 \x01(\v2\n" +
	".proto.KeyR\badminKey\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12f\n" +
	"\x10service_endpoint\x18\x04 \x03(\v2;.com.hedera.hapi.node.addressbook.RegisteredServiceEndpointR\x0fserviceEndpointB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_registered_node_update_proto_rawDescOnce sync.Once
	file_registered_node_update_proto_rawDescData []byte
)

func file_registered_node_update_proto_rawDescGZIP() []byte {
	file_registered_node_update_proto_rawDescOnce.Do(func() {
		file_registered_node_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registered_node_update_proto_rawDesc), len(file_registered_node_update_proto_rawDesc)))
	})
	return file_registered_node_update_proto_rawDescData
}

var file_registered_node_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_registered_node_update_proto_goTypes = []any{
	(*RegisteredNodeUpdateTransactionBody)(nil), // 0: com.hedera.hapi.node.addressbook.RegisteredNodeUpdateTransactionBody
	(*Key)(nil),                       // 1: proto.Key
	(*wrapperspb.StringValue)(nil),    // 2: google.protobuf.StringValue
	(*RegisteredServiceEndpoint)(nil), // 3: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint
}
var file_registered_node_update_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.node.addressbook.RegisteredNodeUpdateTransactionBody.admin_key:type_name -> proto.Key
	2, // 1: com.hedera.hapi.node.addressbook.RegisteredNodeUpdateTransactionBody.description:type_name -> google.protobuf.StringValue
	3, // 2: com.hedera.hapi.node.addressbook.RegisteredNodeUpdateTransactionBody.service_endpoint:type_name -> com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_registered_node_update_proto_init() }
func file_registered_node_update_proto_init() {
	if File_registered_node_update_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_registered_service_endpoint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registered_node_update_proto_rawDesc), len(file_registered_node_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registered_node_update_proto_goTypes,
		DependencyIndexes: file_registered_node_update_proto_depIdxs,
		MessageInfos:      file_registered_node_update_proto_msgTypes,
	}.Build()
	File_registered_node_update_proto = out.File
	file_registered_node_update_proto_goTypes = nil
	file_registered_node_update_proto_depIdxs = nil
}
