// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: registered_service_endpoint.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// An enumeration of well-known block node endpoint APIs, and a
// catch-all option for otherwise unknown endpoint APIs.
type RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi int32

const (
	// *
	// Any other API type associated with a block node.<br/>
	// The caller must consult local documentation to determine the
	// correct call semantics.<br/>
	// It is RECOMMENDED to call the detail status endpoint for further
	// information before using this endpoint.
	RegisteredServiceEndpoint_BlockNodeEndpoint_OTHER RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi = 0
	// *
	// The Block Node Status API.
	RegisteredServiceEndpoint_BlockNodeEndpoint_STATUS RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi = 1
	// *
	// The Block Node Publish API.
	RegisteredServiceEndpoint_BlockNodeEndpoint_PUBLISH RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi = 2
	// *
	// The Block Node Subscribe Stream API.
	RegisteredServiceEndpoint_BlockNodeEndpoint_SUBSCRIBE_STREAM RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi = 3
	// *
	// The Block Node State Proof API.
	RegisteredServiceEndpoint_BlockNodeEndpoint_STATE_PROOF RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi = 4
)

// Enum value maps for RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi.
var (
	RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi_name = map[int32]string{
		0: "OTHER",
		1: "STATUS",
		2: "PUBLISH",
		3: "SUBSCRIBE_STREAM",
		4: "STATE_PROOF",
	}
	RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi_value = map[string]int32{
		"OTHER":            0,
		"STATUS":           1,
		"PUBLISH":          2,
		"SUBSCRIBE_STREAM": 3,
		"STATE_PROOF":      4,
	}
)

func (x RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi) Enum() *RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi {
	p := new(RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi)
	*p = x
	return p
}

func (x RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi) Descriptor() protoreflect.EnumDescriptor {
	return file_registered_service_endpoint_proto_enumTypes[0].Descriptor()
}

func (RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi) Type() protoreflect.EnumType {
	return &file_registered_service_endpoint_proto_enumTypes[0]
}

func (x RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi.Descriptor instead.
func (RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi) EnumDescriptor() ([]byte, []int) {
	return file_registered_service_endpoint_proto_rawDescGZIP(), []int{0, 0, 0}
}

// *
// A registered network node endpoint.<br/>
// Each registered network node in the global address book publishes one or
// more endpoints which enable the nodes to communicate both with other
// nodes and with clients to receive requests.
//
// This message supports a TCP/UDP port and IP address (V4 or V6),
// or MAY include a FQDN _instead of_ an IP address.<br/>
type RegisteredServiceEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// An IP address or fully qualified domain name.
	// <p>
	// This oneof is REQUIRED.
	//
	// Types that are valid to be assigned to Address:
	//
	//	*RegisteredServiceEndpoint_IpAddress
	//	*RegisteredServiceEndpoint_DomainName
	Address isRegisteredServiceEndpoint_Address `protobuf_oneof:"address"`
	// *
	// A network port to use.
	// <p>
	// This value MUST be between 0 and 65535, inclusive.<br/>
	// This value is REQUIRED.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// *
	// A flag indicating if this endpoint requires TLS.
	// <p>
	// If this value is set true, then connections to this endpoint MUST
	// enable TLS.
	// <p>
	// TLS endpoints MAY use self-signed certificates for this purpose,
	// but use of self-signed certificates SHOULD be limited to testing and
	// development environments to ensure production environments meet all
	// expected characteristics for transport layer security.
	RequiresTls bool `protobuf:"varint,4,opt,name=requires_tls,json=requiresTls,proto3" json:"requires_tls,omitempty"`
	// *
	// An endpoint type.<br/>
	// This declares the type of registered node endpoint and includes any
	// type-specific fields.
	// <p>
	// This oneof is REQUIRED.
	//
	// Types that are valid to be assigned to EndpointType:
	//
	//	*RegisteredServiceEndpoint_BlockNode
	//	*RegisteredServiceEndpoint_MirrorNode
	//	*RegisteredServiceEndpoint_RpcRelay
	EndpointType  isRegisteredServiceEndpoint_EndpointType `protobuf_oneof:"endpoint_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredServiceEndpoint) Reset() {
	*x = RegisteredServiceEndpoint{}
	mi := &file_registered_service_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredServiceEndpoint) ProtoMessage() {}

func (x *RegisteredServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_registered_service_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredServiceEndpoint.ProtoReflect.Descriptor instead.
func (*RegisteredServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_registered_service_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *RegisteredServiceEndpoint) GetAddress() isRegisteredServiceEndpoint_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RegisteredServiceEndpoint) GetIpAddress() []byte {
	if x != nil {
		if x, ok := x.Address.(*RegisteredServiceEndpoint_IpAddress); ok {
			return x.IpAddress
		}
	}
	return nil
}

func (x *RegisteredServiceEndpoint) GetDomainName() string {
	if x != nil {
		if x, ok := x.Address.(*RegisteredServiceEndpoint_DomainName); ok {
			return x.DomainName
		}
	}
	return ""
}

func (x *RegisteredServiceEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisteredServiceEndpoint) GetRequiresTls() bool {
	if x != nil {
		return x.RequiresTls
	}
	return false
}

func (x *RegisteredServiceEndpoint) GetEndpointType() isRegisteredServiceEndpoint_EndpointType {
	if x != nil {
		return x.EndpointType
	}
	return nil
}

func (x *RegisteredServiceEndpoint) GetBlockNode() *RegisteredServiceEndpoint_BlockNodeEndpoint {
	if x != nil {
		if x, ok := x.EndpointType.(*RegisteredServiceEndpoint_BlockNode); ok {
			return x.BlockNode
		}
	}
	return nil
}

func (x *RegisteredServiceEndpoint) GetMirrorNode() *RegisteredServiceEndpoint_MirrorNodeEndpoint {
	if x != nil {
		if x, ok := x.EndpointType.(*RegisteredServiceEndpoint_MirrorNode); ok {
			return x.MirrorNode
		}
	}
	return nil
}

func (x *RegisteredServiceEndpoint) GetRpcRelay() *RegisteredServiceEndpoint_RpcRelayEndpoint {
	if x != nil {
		if x, ok := x.EndpointType.(*RegisteredServiceEndpoint_RpcRelay); ok {
			return x.RpcRelay
		}
	}
	return nil
}

type isRegisteredServiceEndpoint_Address interface {
	isRegisteredServiceEndpoint_Address()
}

type RegisteredServiceEndpoint_IpAddress struct {
	// *
	// A 32-bit IPv4 address or 128-bit IPv6 address.<br/>
	// This is the address of the endpoint, encoded in pure "big-endian"
	// (i.e. left to right) order (e.g. IPv4 address `127.0.0.1` has
	// hex bytes in the order `7F`, `00`, `00`, `01`.<br/>
	// IPv6 address `::1` has hex bytes `00`, `00`, `00`, `00`, `00`, `00`,
	// `00`, `00`, `00`, `00`, `00`, `00`, `00`, `00`, `00`, `01`).
	IpAddress []byte `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3,oneof"`
}

type RegisteredServiceEndpoint_DomainName struct {
	// *
	// A node domain name.
	// <p>
	// This MUST be the fully qualified domain name of the node.<br/>
	// This value MUST NOT exceed 250 ASCII characters.<br/>
	// This value MUST meet all other DNS name requirements.
	DomainName string `protobuf:"bytes,2,opt,name=domain_name,json=domainName,proto3,oneof"`
}

func (*RegisteredServiceEndpoint_IpAddress) isRegisteredServiceEndpoint_Address() {}

func (*RegisteredServiceEndpoint_DomainName) isRegisteredServiceEndpoint_Address() {}

type isRegisteredServiceEndpoint_EndpointType interface {
	isRegisteredServiceEndpoint_EndpointType()
}

type RegisteredServiceEndpoint_BlockNode struct {
	// *
	// A Block Node.<br/>
	// A Block Node stores the block chain, provides content proof services,
	// and delivers the block stream to other clients.
	BlockNode *RegisteredServiceEndpoint_BlockNodeEndpoint `protobuf:"bytes,5,opt,name=block_node,json=blockNode,proto3,oneof"`
}

type RegisteredServiceEndpoint_MirrorNode struct {
	// *
	// A Mirror Node.<br/>
	// A Mirror Node is an advanced indexing and query service that provides
	// fast and flexible access to query the block chain and transaction
	// history. A Mirror Node typically stores all recent blockchain data,
	// and some store the entire history of the network.
	MirrorNode *RegisteredServiceEndpoint_MirrorNodeEndpoint `protobuf:"bytes,6,opt,name=mirror_node,json=mirrorNode,proto3,oneof"`
}

type RegisteredServiceEndpoint_RpcRelay struct {
	// *
	// A RPC Relay.<br/>
	// A RPC Relay is a proxy and translator between EVM tooling and a
	// Hiero consensus network.
	RpcRelay *RegisteredServiceEndpoint_RpcRelayEndpoint `protobuf:"bytes,7,opt,name=rpc_relay,json=rpcRelay,proto3,oneof"`
}

func (*RegisteredServiceEndpoint_BlockNode) isRegisteredServiceEndpoint_EndpointType() {}

func (*RegisteredServiceEndpoint_MirrorNode) isRegisteredServiceEndpoint_EndpointType() {}

func (*RegisteredServiceEndpoint_RpcRelay) isRegisteredServiceEndpoint_EndpointType() {}

// *
// A message indicating this endpoint is a Block Node endpoint.<br/>
// Block Node endpoints offer one of several block node APIs, so this
// endpoint entry also declares which well-known Block Node API is
// supported by this endpoint, or "OTHER" for less common APIs.
type RegisteredServiceEndpoint_BlockNodeEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// An indicator of what API this endpoint supports.
	// <p>
	// This field is REQUIRED.
	EndpointApi   RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi `protobuf:"varint,1,opt,name=endpoint_api,json=endpointApi,proto3,enum=com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi" json:"endpoint_api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredServiceEndpoint_BlockNodeEndpoint) Reset() {
	*x = RegisteredServiceEndpoint_BlockNodeEndpoint{}
	mi := &file_registered_service_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredServiceEndpoint_BlockNodeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredServiceEndpoint_BlockNodeEndpoint) ProtoMessage() {}

func (x *RegisteredServiceEndpoint_BlockNodeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_registered_service_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredServiceEndpoint_BlockNodeEndpoint.ProtoReflect.Descriptor instead.
func (*RegisteredServiceEndpoint_BlockNodeEndpoint) Descriptor() ([]byte, []int) {
	return file_registered_service_endpoint_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegisteredServiceEndpoint_BlockNodeEndpoint) GetEndpointApi() RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi {
	if x != nil {
		return x.EndpointApi
	}
	return RegisteredServiceEndpoint_BlockNodeEndpoint_OTHER
}

// *
// A message indicating this endpoint is a Mirror Node endpoint.
type RegisteredServiceEndpoint_MirrorNodeEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredServiceEndpoint_MirrorNodeEndpoint) Reset() {
	*x = RegisteredServiceEndpoint_MirrorNodeEndpoint{}
	mi := &file_registered_service_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredServiceEndpoint_MirrorNodeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredServiceEndpoint_MirrorNodeEndpoint) ProtoMessage() {}

func (x *RegisteredServiceEndpoint_MirrorNodeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_registered_service_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredServiceEndpoint_MirrorNodeEndpoint.ProtoReflect.Descriptor instead.
func (*RegisteredServiceEndpoint_MirrorNodeEndpoint) Descriptor() ([]byte, []int) {
	return file_registered_service_endpoint_proto_rawDescGZIP(), []int{0, 1}
}

// *
// A message indicating this endpoint is a RPC Relay endpoint.
type RegisteredServiceEndpoint_RpcRelayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredServiceEndpoint_RpcRelayEndpoint) Reset() {
	*x = RegisteredServiceEndpoint_RpcRelayEndpoint{}
	mi := &file_registered_service_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredServiceEndpoint_RpcRelayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredServiceEndpoint_RpcRelayEndpoint) ProtoMessage() {}

func (x *RegisteredServiceEndpoint_RpcRelayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_registered_service_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredServiceEndpoint_RpcRelayEndpoint.ProtoReflect.Descriptor instead.
func (*RegisteredServiceEndpoint_RpcRelayEndpoint) Descriptor() ([]byte, []int) {
	return file_registered_service_endpoint_proto_rawDescGZIP(), []int{0, 2}
}

var File_registered_service_endpoint_proto protoreflect.FileDescriptor

const file_registered_service_endpoint_proto_rawDesc = "" +
	"\n" +
	"!registered_service_endpoint.proto\x12 com.hedera.hapi.node.addressbook\"\x9c\x06\n" +
	"\x19RegisteredServiceEndpoint\x12\x1f\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\fH\x00R\tipAddress\x12!\n" +
	"\vdomain_name\x18\x02 \x01(\tH\x00R\n" +
	"domainName\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12!\n" +
	"\frequires_tls\x18\x04 \x01(\bR\vrequiresTls\x12n\n" +
	"\n" +
	"block_node\x18\x05 \x01(\v2M.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpointH\x01R\tblockNode\x12q\n" +
	"\vmirror_node\x18\x06 \x01(\v2N.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.MirrorNodeEndpointH\x01R\n" +
	"mirrorNode\x12k\n" +
	"\trpc_relay\x18\a \x01(\v2L.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.RpcRelayEndpointH\x01R\brpcRelay\x1a\xed\x01\n" +
	"\x11BlockNodeEndpoint\x12}\n" +
	"\fendpoint_api\x18\x01 \x01(\x0e2Z.com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint.BlockNodeApiR\vendpointApi\"Y\n" +
	"\fBlockNodeApi\x12\t\n" +
	"\x05OTHER\x10\x00\x12\n" +
	"\n" +
	"\x06STATUS\x10\x01\x12\v\n" +
	"\aPUBLISH\x10\x02\x12\x14\n" +
	"\x10SUBSCRIBE_STREAM\x10\x03\x12\x0f\n" +
	"\vSTATE_PROOF\x10\x04\x1a\x14\n" +
	"\x12MirrorNodeEndpoint\x1a\x12\n" +
	"\x10RpcRelayEndpointB\t\n" +
	"\aaddressB\x0f\n" +
	"\rendpoint_typeB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_registered_service_endpoint_proto_rawDescOnce sync.Once
	file_registered_service_endpoint_proto_rawDescData []byte
)

func file_registered_service_endpoint_proto_rawDescGZIP() []byte {
	file_registered_service_endpoint_proto_rawDescOnce.Do(func() {
		file_registered_service_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registered_service_endpoint_proto_rawDesc), len(file_registered_service_endpoint_proto_rawDesc)))
	})
	return file_registered_service_endpoint_proto_rawDescData
}

var file_registered_service_endpoint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_registered_service_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registered_service_endpoint_proto_goTypes = []any{
	(RegisteredServiceEndpoint_BlockNodeEndpoint_BlockNodeApi)(0), // 0: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint.BlockNodeApi
	(*RegisteredServiceEndpoint)(nil),                             // 1: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint
	(*RegisteredServiceEndpoint_BlockNodeEndpoint)(nil),           // 2: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint
	(*RegisteredServiceEndpoint_MirrorNodeEndpoint)(nil),          // 3: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.MirrorNodeEndpoint
	(*RegisteredServiceEndpoint_RpcRelayEndpoint)(nil),            // 4: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.RpcRelayEndpoint
}
var file_registered_service_endpoint_proto_depIdxs = []int32{
	2, // 0: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.block_node:type_name -> com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint
	3, // 1: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.mirror_node:type_name -> com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.MirrorNodeEndpoint
	4, // 2: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.rpc_relay:type_name -> com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.RpcRelayEndpoint
	0, // 3: com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint.endpoint_api:type_name -> com.hedera.hapi.node.addressbook.RegisteredServiceEndpoint.BlockNodeEndpoint.BlockNodeApi
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_registered_service_endpoint_proto_init() }
func file_registered_service_endpoint_proto_init() {
	if File_registered_service_endpoint_proto != nil {
		return
	}
	file_registered_service_endpoint_proto_msgTypes[0].OneofWrappers = []any{
		(*RegisteredServiceEndpoint_IpAddress)(nil),
		(*RegisteredServiceEndpoint_DomainName)(nil),
		(*RegisteredServiceEndpoint_BlockNode)(nil),
		(*RegisteredServiceEndpoint_MirrorNode)(nil),
		(*RegisteredServiceEndpoint_RpcRelay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registered_service_endpoint_proto_rawDesc), len(file_registered_service_endpoint_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registered_service_endpoint_proto_goTypes,
		DependencyIndexes: file_registered_service_endpoint_proto_depIdxs,
		EnumInfos:         file_registered_service_endpoint_proto_enumTypes,
		MessageInfos:      file_registered_service_endpoint_proto_msgTypes,
	}.Build()
	File_registered_service_endpoint_proto = out.File
	file_registered_service_endpoint_proto_goTypes = nil
	file_registered_service_endpoint_proto_depIdxs = nil
}
