// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: roster.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A single roster in the network state.
// <p>
// The roster SHALL be a list of `RosterEntry` objects.
type Roster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// List of roster entries, one per consensus node.
	// <p>
	// This list SHALL contain roster entries in natural order of ascending node ids.
	// This list SHALL NOT be empty.<br/>
	RosterEntries []*RosterEntry `protobuf:"bytes,1,rep,name=roster_entries,json=rosterEntries,proto3" json:"roster_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Roster) Reset() {
	*x = Roster{}
	mi := &file_roster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Roster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roster) ProtoMessage() {}

func (x *Roster) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roster.ProtoReflect.Descriptor instead.
func (*Roster) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{0}
}

func (x *Roster) GetRosterEntries() []*RosterEntry {
	if x != nil {
		return x.RosterEntries
	}
	return nil
}

// *
// A single roster entry in the network state.
//
// Each roster entry SHALL encapsulate the elements required
// to manage node participation in the Threshold Signature Scheme (TSS).<br/>
// All fields are REQUIRED.
type RosterEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A consensus node identifier.
	// <p>
	// Node identifiers SHALL be unique _within_ a ledger,
	// and MUST NOT be repeated _between_ shards and realms.
	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// *
	// A consensus weight.
	// <p>
	// Each node SHALL have a weight of zero or more in consensus calculations.<br/>
	// The sum of the weights of all nodes in the roster SHALL form the total weight of the system,
	// and each node's individual weight SHALL be proportional to that sum.<br/>
	Weight uint64 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// *
	// An RSA public certificate used for signing gossip events.
	// <p>
	// This value SHALL be a certificate of a type permitted for gossip
	// signatures.<br/>
	// This value SHALL be the DER encoding of the certificate presented.<br/>
	// This field is REQUIRED and MUST NOT be empty.
	GossipCaCertificate []byte `protobuf:"bytes,3,opt,name=gossip_ca_certificate,json=gossipCaCertificate,proto3" json:"gossip_ca_certificate,omitempty"`
	// *
	// A list of service endpoints for gossip.
	// <p>
	// These endpoints SHALL represent the published endpoints to which other
	// consensus nodes may _gossip_ transactions.<br/>
	// If the network configuration value `gossipFqdnRestricted` is set, then
	// all endpoints in this list SHALL supply only IP address.<br/>
	// If the network configuration value `gossipFqdnRestricted` is _not_ set,
	// then endpoints in this list MAY supply either IP address or FQDN, but
	// SHALL NOT supply both values for the same endpoint.<br/>
	// This list SHALL NOT be empty.<br/>
	GossipEndpoint []*ServiceEndpoint `protobuf:"bytes,5,rep,name=gossip_endpoint,json=gossipEndpoint,proto3" json:"gossip_endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RosterEntry) Reset() {
	*x = RosterEntry{}
	mi := &file_roster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosterEntry) ProtoMessage() {}

func (x *RosterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosterEntry.ProtoReflect.Descriptor instead.
func (*RosterEntry) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{1}
}

func (x *RosterEntry) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RosterEntry) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RosterEntry) GetGossipCaCertificate() []byte {
	if x != nil {
		return x.GossipCaCertificate
	}
	return nil
}

func (x *RosterEntry) GetGossipEndpoint() []*ServiceEndpoint {
	if x != nil {
		return x.GossipEndpoint
	}
	return nil
}

var File_roster_proto protoreflect.FileDescriptor

const file_roster_proto_rawDesc = "" +
	"\n" +
	"\froster.proto\x12!com.hedera.hapi.node.state.roster\x1a\x11basic_types.proto\"_\n" +
	"\x06Roster\x12U\n" +
	"\x0eroster_entries\x18\x01 \x03(\v2..com.hedera.hapi.node.state.roster.RosterEntryR\rrosterEntries\"\xb9\x01\n" +
	"\vRosterEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x04R\x06weight\x122\n" +
	"\x15gossip_ca_certificate\x18\x03 \x01(\fR\x13gossipCaCertificate\x12?\n" +
	"\x0fgossip_endpoint\x18\x05 \x03(\v2\x16.proto.ServiceEndpointR\x0egossipEndpointJ\x04\b\x04\x10\x05B&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_roster_proto_rawDescOnce sync.Once
	file_roster_proto_rawDescData []byte
)

func file_roster_proto_rawDescGZIP() []byte {
	file_roster_proto_rawDescOnce.Do(func() {
		file_roster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roster_proto_rawDesc), len(file_roster_proto_rawDesc)))
	})
	return file_roster_proto_rawDescData
}

var file_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_roster_proto_goTypes = []any{
	(*Roster)(nil),          // 0: com.hedera.hapi.node.state.roster.Roster
	(*RosterEntry)(nil),     // 1: com.hedera.hapi.node.state.roster.RosterEntry
	(*ServiceEndpoint)(nil), // 2: proto.ServiceEndpoint
}
var file_roster_proto_depIdxs = []int32{
	1, // 0: com.hedera.hapi.node.state.roster.Roster.roster_entries:type_name -> com.hedera.hapi.node.state.roster.RosterEntry
	2, // 1: com.hedera.hapi.node.state.roster.RosterEntry.gossip_endpoint:type_name -> proto.ServiceEndpoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_roster_proto_init() }
func file_roster_proto_init() {
	if File_roster_proto != nil {
		return
	}
	file_basic_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roster_proto_rawDesc), len(file_roster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roster_proto_goTypes,
		DependencyIndexes: file_roster_proto_depIdxs,
		MessageInfos:      file_roster_proto_msgTypes,
	}.Build()
	File_roster_proto = out.File
	file_roster_proto_goTypes = nil
	file_roster_proto_depIdxs = nil
}
