//*
// # State Signature Transaction
// An signature of a state snapshot gossiped to other nodes.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in [RFC2119](https://www.ietf.org/rfc/rfc2119).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: state_signature_transaction.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// An signature of a state snapshot gossiped to other nodes.
// Each node SHALL hash the root of the merkle tree of a state snapshot every
// round. Once this hash is calculated, it SHOULD be signed with the nodes
// private signing key. This signature, together with the hash SHOULD be added
// to an event as a StateSignatureTransaction.
type StateSignatureTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// The round number corresponding to the round number of the state snapshot
	// being signed.<br/>
	// This number MUST be greater than 0.
	Round int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	// *
	// The signature of state snapshot hash.<br/>
	// This signature MUST be a RSA signature with a maximum length of 384 bytes.<br/>
	// The signature algorithm used MUST be RSASSA-PKCS1-v1_5 with SHA-384.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// *
	// The hash of the state snapshot being signed.<br/>
	// This hash MUST be a SHA-384 hash.
	Hash          []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSignatureTransaction) Reset() {
	*x = StateSignatureTransaction{}
	mi := &file_state_signature_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSignatureTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSignatureTransaction) ProtoMessage() {}

func (x *StateSignatureTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_state_signature_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSignatureTransaction.ProtoReflect.Descriptor instead.
func (*StateSignatureTransaction) Descriptor() ([]byte, []int) {
	return file_state_signature_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *StateSignatureTransaction) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *StateSignatureTransaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *StateSignatureTransaction) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_state_signature_transaction_proto protoreflect.FileDescriptor

const file_state_signature_transaction_proto_rawDesc = "" +
	"\n" +
	"!state_signature_transaction.proto\x12\x1ecom.hedera.hapi.platform.event\"c\n" +
	"\x19StateSignatureTransaction\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x03R\x05round\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hashB)\n" +
	"%com.hedera.hapi.platform.event.legacyP\x01b\x06proto3"

var (
	file_state_signature_transaction_proto_rawDescOnce sync.Once
	file_state_signature_transaction_proto_rawDescData []byte
)

func file_state_signature_transaction_proto_rawDescGZIP() []byte {
	file_state_signature_transaction_proto_rawDescOnce.Do(func() {
		file_state_signature_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_signature_transaction_proto_rawDesc), len(file_state_signature_transaction_proto_rawDesc)))
	})
	return file_state_signature_transaction_proto_rawDescData
}

var file_state_signature_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_signature_transaction_proto_goTypes = []any{
	(*StateSignatureTransaction)(nil), // 0: com.hedera.hapi.platform.event.StateSignatureTransaction
}
var file_state_signature_transaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_state_signature_transaction_proto_init() }
func file_state_signature_transaction_proto_init() {
	if File_state_signature_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_signature_transaction_proto_rawDesc), len(file_state_signature_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_signature_transaction_proto_goTypes,
		DependencyIndexes: file_state_signature_transaction_proto_depIdxs,
		MessageInfos:      file_state_signature_transaction_proto_msgTypes,
	}.Build()
	File_state_signature_transaction_proto = out.File
	file_state_signature_transaction_proto_goTypes = nil
	file_state_signature_transaction_proto_depIdxs = nil
}
