//*
// # Token Burn
// Permanently remove tokens from circulation, akin to how a fiat treasury
// will physically burn worn out bank notes.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: token_burn.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Burns tokens from the Token's treasury Account.
//
// The token MUST have a `supply_key` set and that key MUST NOT
// be an empty `KeyList`.<br/>
// The token `supply_key` MUST sign this transaction.<br/>
// This operation SHALL decrease the total supply for the token type by
// the number of tokens "burned".<br/>
// The total supply for the token type MUST NOT be reduced below zero (`0`)
// by this transaction.<br/>
// The tokens to burn SHALL be deducted from the token treasury account.<br/>
// If the token is a fungible/common type, the amount MUST be specified.<br/>
// If the token is a non-fungible/unique type, the specific serial numbers
// MUST be specified.<br/>
// The global batch size limit (`tokens.nfts.maxBatchSizeBurn`) SHALL set
// the maximum number of individual NFT serial numbers permitted in a single
// `tokenBurn` transaction.
//
// ### Block Stream Effects
// None
type TokenBurnTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A token identifier.
	// <p>
	// This SHALL identify the token type to "burn".<br/>
	// The identified token MUST exist, and MUST NOT be deleted.
	Token *TokenID `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// *
	// An amount to burn from the Treasury Account.
	// <p>
	// This is interpreted as an amount in the smallest possible denomination
	// for the token (10<sup>-decimals</sup> whole tokens).<br/>
	// The balance for the token treasury account MUST contain sufficient
	// tokens to complete this transaction with a non-negative balance.<br/>
	// If this value is equal to zero (`0`), the token SHOULD be a
	// non-fungible/unique type.<br/>
	// If this value is non-zero, the token MUST be a fungible/common type.
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// A list of serial numbers to burn from the Treasury Account.
	// <p>
	// This list MUST NOT contain more entries than the current limit set by
	// the network configuration value `tokens.nfts.maxBatchSizeBurn`.<br/>
	// The treasury account for the token MUST hold each unique token
	// identified in this list.<br/>
	// If this list is not empty, the token MUST be a
	// non-fungible/unique type.<br/>
	// If this list is empty, the token MUST be a fungible/common type.
	SerialNumbers []int64 `protobuf:"varint,3,rep,packed,name=serialNumbers,proto3" json:"serialNumbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBurnTransactionBody) Reset() {
	*x = TokenBurnTransactionBody{}
	mi := &file_token_burn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBurnTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBurnTransactionBody) ProtoMessage() {}

func (x *TokenBurnTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_token_burn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBurnTransactionBody.ProtoReflect.Descriptor instead.
func (*TokenBurnTransactionBody) Descriptor() ([]byte, []int) {
	return file_token_burn_proto_rawDescGZIP(), []int{0}
}

func (x *TokenBurnTransactionBody) GetToken() *TokenID {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenBurnTransactionBody) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TokenBurnTransactionBody) GetSerialNumbers() []int64 {
	if x != nil {
		return x.SerialNumbers
	}
	return nil
}

var File_token_burn_proto protoreflect.FileDescriptor

const file_token_burn_proto_rawDesc = "" +
	"\n" +
	"\x10token_burn.proto\x12\x05proto\x1a\x11basic_types.proto\"~\n" +
	"\x18TokenBurnTransactionBody\x12$\n" +
	"\x05token\x18\x01 \x01(\v2\x0e.proto.TokenIDR\x05token\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12$\n" +
	"\rserialNumbers\x18\x03 \x03(\x03R\rserialNumbersB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_token_burn_proto_rawDescOnce sync.Once
	file_token_burn_proto_rawDescData []byte
)

func file_token_burn_proto_rawDescGZIP() []byte {
	file_token_burn_proto_rawDescOnce.Do(func() {
		file_token_burn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_burn_proto_rawDesc), len(file_token_burn_proto_rawDesc)))
	})
	return file_token_burn_proto_rawDescData
}

var file_token_burn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_burn_proto_goTypes = []any{
	(*TokenBurnTransactionBody)(nil), // 0: proto.TokenBurnTransactionBody
	(*TokenID)(nil),                  // 1: proto.TokenID
}
var file_token_burn_proto_depIdxs = []int32{
	1, // 0: proto.TokenBurnTransactionBody.token:type_name -> proto.TokenID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_token_burn_proto_init() }
func file_token_burn_proto_init() {
	if File_token_burn_proto != nil {
		return
	}
	file_basic_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_burn_proto_rawDesc), len(file_token_burn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_burn_proto_goTypes,
		DependencyIndexes: file_token_burn_proto_depIdxs,
		MessageInfos:      file_token_burn_proto_msgTypes,
	}.Build()
	File_token_burn_proto = out.File
	file_token_burn_proto_goTypes = nil
	file_token_burn_proto_depIdxs = nil
}
