//*
// # Token Dissociate
// Remove association between an account and one or more Hedera Token
// Service (HTS) tokens.
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: token_dissociate.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Dissociate an account from one or more HTS tokens.
//
// If the identified account is not found,
// the transaction SHALL return `INVALID_ACCOUNT_ID`.<br/>
// If the identified account has been deleted,
// the transaction SHALL return `ACCOUNT_DELETED`.<br/>
// If any of the identified tokens is not found,
// the transaction SHALL return `INVALID_TOKEN_REF`.<br/>
// If any of the identified tokens has been deleted,
// the transaction SHALL return `TOKEN_WAS_DELETED`.<br/>
// If an association does not exist for any of the identified tokens,
// the transaction SHALL return `TOKEN_NOT_ASSOCIATED_TO_ACCOUNT`.<br/>
// If the identified account has a nonzero balance for any of the identified
// tokens, and that token is neither deleted nor expired, the
// transaction SHALL return `TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES`.<br/>
// If one of the identified tokens is a fungible/common token that is expired,
// the account MAY disassociate from that token, even if that token balance is
// not zero for that account.<br/>
// If one of the identified tokens is a non-fungible/unique token that is
// expired, the account MUST NOT disassociate if that account holds any
// individual NFT of that token. In this situation the transaction SHALL
// return `TRANSACTION_REQUIRED_ZERO_TOKEN_BALANCES`.<br/>
// The identified account MUST sign this transaction.
//
// ### Block Stream Effects
// None
type TokenDissociateTransactionBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// An account identifier.
	// <p>
	// The identified account SHALL be dissociated from each of the
	// tokens identified in the `tokens` field.
	// This field is REQUIRED and MUST be a valid account identifier.<br/>
	// The identified account MUST exist in state.<br/>
	// The identified account MUST NOT be deleted.<br/>
	// The identified account MUST NOT be expired.
	Account *AccountID `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// *
	// A list of token identifiers.
	// <p>
	// Each token identified in this list SHALL be dissociated from
	// the account identified in the `account` field.<br/>
	// This list MUST NOT be empty.
	// Each entry in this list MUST be a valid token identifier.<br/>
	// Each entry in this list MUST be currently associated to the
	// account identified in `account`.<br/>
	// Entries in this list MAY be expired, if the token type is
	// fungible/common.<br/>
	// Each entry in this list MUST NOT be deleted.
	Tokens        []*TokenID `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDissociateTransactionBody) Reset() {
	*x = TokenDissociateTransactionBody{}
	mi := &file_token_dissociate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDissociateTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDissociateTransactionBody) ProtoMessage() {}

func (x *TokenDissociateTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_token_dissociate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDissociateTransactionBody.ProtoReflect.Descriptor instead.
func (*TokenDissociateTransactionBody) Descriptor() ([]byte, []int) {
	return file_token_dissociate_proto_rawDescGZIP(), []int{0}
}

func (x *TokenDissociateTransactionBody) GetAccount() *AccountID {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *TokenDissociateTransactionBody) GetTokens() []*TokenID {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_token_dissociate_proto protoreflect.FileDescriptor

const file_token_dissociate_proto_rawDesc = "" +
	"\n" +
	"\x16token_dissociate.proto\x12\x05proto\x1a\x11basic_types.proto\"t\n" +
	"\x1eTokenDissociateTransactionBody\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.proto.AccountIDR\aaccount\x12&\n" +
	"\x06tokens\x18\x02 \x03(\v2\x0e.proto.TokenIDR\x06tokensB&\n" +
	"\"com.hederahashgraph.api.proto.javaP\x01b\x06proto3"

var (
	file_token_dissociate_proto_rawDescOnce sync.Once
	file_token_dissociate_proto_rawDescData []byte
)

func file_token_dissociate_proto_rawDescGZIP() []byte {
	file_token_dissociate_proto_rawDescOnce.Do(func() {
		file_token_dissociate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_dissociate_proto_rawDesc), len(file_token_dissociate_proto_rawDesc)))
	})
	return file_token_dissociate_proto_rawDescData
}

var file_token_dissociate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_dissociate_proto_goTypes = []any{
	(*TokenDissociateTransactionBody)(nil), // 0: proto.TokenDissociateTransactionBody
	(*AccountID)(nil),                      // 1: proto.AccountID
	(*TokenID)(nil),                        // 2: proto.TokenID
}
var file_token_dissociate_proto_depIdxs = []int32{
	1, // 0: proto.TokenDissociateTransactionBody.account:type_name -> proto.AccountID
	2, // 1: proto.TokenDissociateTransactionBody.tokens:type_name -> proto.TokenID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_dissociate_proto_init() }
func file_token_dissociate_proto_init() {
	if File_token_dissociate_proto != nil {
		return
	}
	file_basic_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_dissociate_proto_rawDesc), len(file_token_dissociate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_dissociate_proto_goTypes,
		DependencyIndexes: file_token_dissociate_proto_depIdxs,
		MessageInfos:      file_token_dissociate_proto_msgTypes,
	}.Build()
	File_token_dissociate_proto = out.File
	file_token_dissociate_proto_goTypes = nil
	file_token_dissociate_proto_depIdxs = nil
}
