//*
// # Tss Vote Map Key
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tss_vote_map_key.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A key for use in the Threshold Signature Scheme (TSS) TssVoteMaps.
//
// This key SHALL be used to uniquely identify entries in the Vote Maps.
type TssVoteMapKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// A hash of the target roster for the associated value in the map. <br/>
	// This hash uniquely identifies the target roster.
	// <p>
	// This value MUST be set.<br/>
	// This value MUST contain a valid hash.
	RosterHash []byte `protobuf:"bytes,1,opt,name=roster_hash,json=rosterHash,proto3" json:"roster_hash,omitempty"`
	// * The node id of the node that created the TssVote.<br/>
	// This id uniquely identifies the node.
	// <p>
	// This value MUST be set.<br/>
	// This value MUST be a valid node id.
	NodeId        uint64 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TssVoteMapKey) Reset() {
	*x = TssVoteMapKey{}
	mi := &file_tss_vote_map_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TssVoteMapKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TssVoteMapKey) ProtoMessage() {}

func (x *TssVoteMapKey) ProtoReflect() protoreflect.Message {
	mi := &file_tss_vote_map_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TssVoteMapKey.ProtoReflect.Descriptor instead.
func (*TssVoteMapKey) Descriptor() ([]byte, []int) {
	return file_tss_vote_map_key_proto_rawDescGZIP(), []int{0}
}

func (x *TssVoteMapKey) GetRosterHash() []byte {
	if x != nil {
		return x.RosterHash
	}
	return nil
}

func (x *TssVoteMapKey) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

var File_tss_vote_map_key_proto protoreflect.FileDescriptor

const file_tss_vote_map_key_proto_rawDesc = "" +
	"\n" +
	"\x16tss_vote_map_key.proto\x12\x1ecom.hedera.hapi.node.state.tss\"I\n" +
	"\rTssVoteMapKey\x12\x1f\n" +
	"\vroster_hash\x18\x01 \x01(\fR\n" +
	"rosterHash\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x04R\x06nodeIdB)\n" +
	"%com.hedera.hapi.node.state.tss.legacyP\x01b\x06proto3"

var (
	file_tss_vote_map_key_proto_rawDescOnce sync.Once
	file_tss_vote_map_key_proto_rawDescData []byte
)

func file_tss_vote_map_key_proto_rawDescGZIP() []byte {
	file_tss_vote_map_key_proto_rawDescOnce.Do(func() {
		file_tss_vote_map_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tss_vote_map_key_proto_rawDesc), len(file_tss_vote_map_key_proto_rawDesc)))
	})
	return file_tss_vote_map_key_proto_rawDescData
}

var file_tss_vote_map_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tss_vote_map_key_proto_goTypes = []any{
	(*TssVoteMapKey)(nil), // 0: com.hedera.hapi.node.state.tss.TssVoteMapKey
}
var file_tss_vote_map_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tss_vote_map_key_proto_init() }
func file_tss_vote_map_key_proto_init() {
	if File_tss_vote_map_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tss_vote_map_key_proto_rawDesc), len(file_tss_vote_map_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tss_vote_map_key_proto_goTypes,
		DependencyIndexes: file_tss_vote_map_key_proto_depIdxs,
		MessageInfos:      file_tss_vote_map_key_proto_msgTypes,
	}.Build()
	File_tss_vote_map_key_proto = out.File
	file_tss_vote_map_key_proto_goTypes = nil
	file_tss_vote_map_key_proto_depIdxs = nil
}
