version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gosec:
      excludes:
        - G115
