version: "3"

tasks:
    update-addressbook:
        cmds:
            - go test ./sdk -tags="abnet" -v -run TestIntegrationAddressBookQueryPreviewnet
            - go test ./sdk -tags="abnet" -v -run TestIntegrationAddressBookQueryTestnet
            - go test ./sdk -tags="abnet" -v -run TestIntegrationAddressBookQueryMainnet

    run-examples:
        cmds:
            - |
              for example in examples/*; do
                 dir_name=$(basename "$example")
                  # Skip the consensus_pub_sub_chunked directory
                  if [ "$dir_name" == "consensus_pub_sub_chunked" ] || [ "$dir_name" == "initialize-client-with-mirror-node-adress-book" ] || [ "$dir_name" == "batch_transaction" ]; then
                      echo "Skipping $example"
                      continue
                  fi
                  if [ -d "$example" ]; then

                      pushd "$example" > /dev/null
                      if [ -f main.go ]; then
                          echo "Running $example/main.go"
                          HEDERA_NETWORK="localhost" go run main.go
                      fi
                      popd > /dev/null
                  fi
              done

