version: "3"

tasks:
    update-addressbook:
        cmds:
            - go test ./sdk -tags="DAB" -v -run TestIntegrationAddressBookQueryPreviewnet
            - go test ./sdk -tags="DAB" -v -run TestIntegrationAddressBookQueryTestnet
            - go test ./sdk -tags="DAB" -v -run TestIntegrationAddressBookQueryMainnet

    run-examples:
        cmds:
            - |
              for example in examples/*; do
                  dir_name=$(basename "$example")
                  case "$dir_name" in
                      consensus_pub_sub | \
                      consensus_pub_sub_chunked | \
                      consensus_pub_sub_with_submit_key | \
                      initialize-client-with-mirror-node-adress-book | \
                      batch_transaction | \
                      long_term_scheduled_transactions | \
                      mirror_node_contract_queries | \
                      fee_estimate_query)
                          echo "Skipping $example"
                          continue
                          ;;
                  esac
                  if [ -d "$example" ] && [ -f "$example/main.go" ]; then
                      echo "Running $example/main.go"
                      pushd "$example" > /dev/null
                      HEDERA_NETWORK="localhost" go run main.go
                      popd > /dev/null
                  fi
              done

